### ISSUE TITLE
pg_upgrade does not copy citus metadata table contents set table dependencies

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#980] opened 2016-11-12 01:19 UTC
After fixing #963 and #964 we can create citus metadata tables during pg_upgrade. But we still can not : 
- copy metadata table contents
- set current sequence values
- establish dependencies between distributed tables and citus extension in pg_depend
- register truncate trigger with distributed tables

We use some pre/post script to complete migration. It would be nice if there is a more streamlined method here.

**Comment by mtuncer** [comment] 2016-11-12 01:41
https://github.com/citusdata/citus/issues/99 is related to this one

**Comment by ozgune** [comment] 2016-11-29 22:56
@mtuncer -- This issue looks like a duplicate of #99. I'm therefore adding a minor edit to your description and closing #99 in favor of this issue. Please let me know if we need to reopen #99.

I'm also noting #169 as a semi-related issue on taking distributed backups.

**Comment by marcocitus** [comment] 2019-10-01 22:05
Fixed by https://github.com/citusdata/citus/pull/2877

**Closed by marcocitus** 2019-10-01 22:05 UTC
