### ISSUE TITLE
The result of join of two distributed tables could be wrong

### ISSUE THREAD

**Issue by ChenHuajun** [citusdata/citus#1258] opened 2017-02-27 12:28 UTC
join distributed table will got a wrong result

# environment
- PostgreSQL9.6.2
- citus 6.1.0

# how to reproduct
## 1. ddl
tb1 is a normal distributed table with 32 shard on 8 workers

	create table tb1(id int,c1 int);
	set citus.shard_count = 32;
	set citus.shard_replication_factor = 1;
	select create_distributed_table('tb1','id');

tb2 is a one shard distributed table

	create table tb2(id int,c2 int);
	set citus.shard_count = 1;
	set citus.shard_replication_factor = 1;
	select create_distributed_table('tb2','id');

node: i had tried set shard_count to  1,2 and 5 , the reuslt is same 
## 2. insert data
	
	insert into tb1 values(1,1);
	insert into tb1 values(2,2);
	insert into tb1 values(3,3);
	insert into tb2 values(2,2);
	insert into tb2 values(4,4);

## 3. run join query

    postgres=# select * from tb1 inner join tb2 on(tb1.id=tb2.id);
     id | c1 | id | c2 
    ----+----+----+----
      2 |  2 |  2 |  2
    (1 row)

### the plan

	postgres=# explain select * from tb1 inner join tb2 on(tb1.id=tb2.id);
	                                        QUERY PLAN                                        
	------------------------------------------------------------------------------------------
	 Distributed Query into pg_merge_job_10964
	   Executor: Real-Time
	   Task Count: 32
	   Tasks Shown: One of 32
	   ->  Task
	         Node: host=192.168.0.1 port=5432 dbname=lbi
	         ->  Merge Join  (cost=317.01..711.38 rows=25538 width=16)
	               Merge Cond: (tb1.id = tb2.id)
	               ->  Sort  (cost=158.51..164.16 rows=2260 width=8)
	                     Sort Key: tb1.id
	                     ->  Seq Scan on tb1_102776 tb1  (cost=0.00..32.60 rows=2260 width=8)
	               ->  Sort  (cost=158.51..164.16 rows=2260 width=8)
	                     Sort Key: tb2.id
	                     ->  Seq Scan on tb2_102842 tb2  (cost=0.00..32.60 rows=2260 width=8)
	 Master Query
	   ->  Seq Scan on pg_merge_job_10964  (cost=0.00..0.00 rows=0 width=0)
	(16 rows)

### sql run on worker1
	
	< 2017-02-28 04:13:47.853 CST 15104 > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:13:47.853 CST 15103 > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:13:47.853 CST 15102 > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:13:47.853 CST 15101 > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:13:47.853 CST 15104 > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102800 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:13:47.853 CST 15103 > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102792 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:13:47.854 CST 15101 > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102776 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:13:47.854 CST 15102 > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102784 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:13:47.856 CST 15105 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.857 CST 15106 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.857 CST 15107 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.857 CST 15108 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.858 CST 15109 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.858 CST 15110 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.863 CST 15111 > LOG:  statement: COPY tb2_102842 TO STDOUT
	< 2017-02-28 04:13:47.868 CST 15112 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.869 CST 15113 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.869 CST 15114 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.870 CST 15115 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.870 CST 15116 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.870 CST 15117 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.875 CST 15118 > LOG:  statement: SELECT rolname FROM pg_class JOIN pg_roles ON (pg_roles.oid = pg_class.relowner) WHERE pg_class.oid = 'tb2_102842'::regclass
	< 2017-02-28 04:13:47.880 CST 15119 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')
	< 2017-02-28 04:13:47.881 CST 15121 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')
	< 2017-02-28 04:13:47.881 CST 15120 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')
	< 2017-02-28 04:13:47.882 CST 15122 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')
	< 2017-02-28 04:13:47.882 CST 15123 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')
	< 2017-02-28 04:13:47.882 CST 15124 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')
	< 2017-02-28 04:13:47.887 CST 15125 > LOG:  statement: SELECT master_get_table_ddl_events('tb2_102842')

### sql run on worker2~worker8

	< 2017-02-28 04:11:48.922 CST > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:11:48.922 CST > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:11:48.922 CST > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:11:48.922 CST > LOG:  statement: SELECT worker_fetch_regular_table  ('tb2_102842', 0, '{192.168.0.1}', '{5432}')
	< 2017-02-28 04:11:48.966 CST > LOG:  statement: CREATE TABLE public.tb2_102842 (id integer, c2 integer)
	< 2017-02-28 04:11:48.968 CST > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102793 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:11:48.968 CST > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102785 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:11:48.968 CST > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102801 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT
	< 2017-02-28 04:11:48.968 CST > LOG:  statement: COPY (SELECT tb1.id, tb1.c1, tb2.id, tb2.c2 FROM (tb1_102777 tb1 JOIN tb2_102842 tb2 ON ((tb1.id = tb2.id))) WHERE true) TO STDOUT

Table tb2_102842 was created on all workers

## 4. insert more data to one shard distributed table(tb2)

	insert into tb2 values(3,3);

### sql run on worker1

	< 2017-02-28 04:19:00.038 CST 15097 > LOG:  execute <unnamed>: INSERT INTO public.tb2_102842 (id, c2) VALUES (3, 3)

the new data only be inserted into worker1 

## 5. run join query again

	postgres=# select * from tb1 inner join tb2 on(tb1.id=tb2.id);
	 id | c1 | id | c2 
	----+----+----+----
	  2 |  2 |  2 |  2
	(1 row)

The query result is wrong!
The correct one should be:

	postgres=# select * from tb1 inner join tb2 on(tb1.id=tb2.id);
	 id | c1 | id | c2 
	----+----+----+----
	  2 |  2 |  2 |  2
	  3 |  3 |  3 |  3
	(1 row)

**Comment by marcocitus** [comment] 2017-02-27 13:32
This is odd, but expected behaviour. In early versions of Citus(DB), tables were append-only and shards were read-only. You would add new data by adding new shards. To perform a join between a distributed table and a single-shard table, Citus copies the shard to all nodes and keep it cached, which would be correct under the assumption that the shard never changes. However, we've since integrated pg_shard into Citus, which added the ability to perform DML commands on distributed as well as single-shard tables, meaning the assumption no longer holds.

To resolve this, we've introduced the `create_reference_table` UDF, which you can use to create a single-shard table that is replicated to all nodes. If you use `create_reference_table` for `tb2`, then you should get the correct join result.

**Comment by marcocitus** [comment] 2017-02-27 13:51
You can also use `SELECT master_expire_table_cache('tb2')` to clear the cached shards.

**Comment by marcocitus** [comment] 2017-02-27 13:53
Closing this issue in favour of #1259.

**Closed by marcocitus** 2017-02-27 13:53 UTC

**Comment by ChenHuajun** [comment] 2017-03-04 03:54
i had tried set shard_count to 1,2 and 5 (citus.large_table_shard_count=4) for tb2, the reuslt is same, so it's not only  the problem of single-shard table
