### ISSUE TITLE
Double quoted column names fails if there is data in table before distributing

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#1458] opened 2017-06-18 15:18 UTC
If there is data inside a table with double quoted column names, `create_distributed_table()` and `create_reference_table()` fail.

```sql
CREATE TABLE test_table
(
  id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  "fileHost" character varying(255)
);

insert into test_table values ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'test');

SELECT create_distributed_table('test_table', 'tenant_id');
ERROR:  column "filehost" of relation "test_table_102307" does not exist
CONTEXT:  while executing command on localhost:9700
```

```sql

CREATE TABLE public.tenant
(
  id uuid NOT NULL,
  name character varying(255),
  "group" character varying(255)
);

insert into tenant values ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'test', 'test');

SELECT create_reference_table('tenant');
ERROR:  syntax error at or near "group"
CONTEXT:  while executing command on localhost:9701
```

Note that if you distribute empty table and then insert data, it works fine.

This issue came across in citus users group.

**Comment by marcocitus** [comment] 2017-06-22 14:25
This is fixed in master but needs a regression test.

**Closed** 2017-06-22 15:14 UTC

**Comment by marcocitus** [comment] 2017-06-30 15:05
We should consider backporting the fix for this (https://github.com/citusdata/citus/pull/1402/commits/2cd358ad1ae05662b33dd173d5b694c65ed1a0e1) since it also affects COPY.
