### ISSUE TITLE
Segfault while running a real-time `SELECT`

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2092] opened 2018-04-11 07:41 UTC
We've observed the same issue in both Citus 7.2 and 7.3 on 3-4 different clusters. 

As far as I understand, it is not related to the query we run. For example, a query (table names/column names replaced) that we've seen the issue is `select min(value_1) from users_table where value_3 is null;` or another query on github events data: `SELECT login, count(*)\nFROM    github_events ge\nJOIN    github_users gu\nON ge.user_id = gu.user_id\nWHERE event_type = 'CreateEvent' AND\npayload @> '{\"ref_type\": \"repository\"}'\nGROUP BY login\nORDER BY "...)`

```
(gdb) bt
#0  StartPlacementListConnection (flags=16, placementAccessList=0x0, userName=0x175ce90 "citus")
    at connection/placement_connection.c:305
#1  0x00007fbed0604e1d in MultiClientPlacementConnectStart (placementAccessList=<optimized out>,
    userName=<optimized out>) at executor/multi_client_executor.c:201
#2  0x00007fbed06060be in ManageTaskExecution (executionStats=0x7ffcb8ea2170,
    executionStatus=<optimized out>, taskExecution=0x1629e48, task=0x161b528)
    at executor/multi_real_time_executor.c:306
#3  MultiRealTimeExecute (job=<optimized out>) at executor/multi_real_time_executor.c:143
#4  0x00007fbed06065c2 in RealTimeExecScan (node=<optimized out>)
    at executor/multi_real_time_executor.c:1086
#5  0x00000000006071d6 in ExecProcNode (node=0x161a158)
    at ../../../src/include/executor/executor.h:250
#6  ExecSort (pstate=0x1619ee8) at nodeSort.c:106
#7  0x00000000005fec49 in ExecProcNode (node=0x1619ee8)
    at ../../../src/include/executor/executor.h:250
#8  ExecLimit (pstate=0x1619778) at nodeLimit.c:95
#9  0x00000000005e70f2 in ExecProcNode (node=0x1619778)
    at ../../../src/include/executor/executor.h:250
#10 ExecutePlan (execute_once=<optimized out>, dest=0x1557ad8, direction=<optimized out>,
    numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT,
    use_parallel_mode=<optimized out>, planstate=0x1619778, estate=0x1619518) at execMain.c:1722
#11 standard_ExecutorRun (queryDesc=0x159df50, direction=<optimized out>, count=0,
    execute_once=<optimized out>) at execMain.c:363
#12 0x00007fbecf0b8fd5 in pgss_ExecutorRun (queryDesc=0x159df50, direction=ForwardScanDirection,
    count=0, execute_once=<optimized out>) at pg_stat_statements.c:889
#13 0x0000000000709c7c in PortalRunSelect (portal=portal@entry=0x1588168,
    forward=forward@entry=1 '\001', count=0, count@entry=9223372036854775807,
    dest=dest@entry=0x1557ad8) at pquery.c:932
#14 0x000000000070aff0 in PortalRun (portal=portal@entry=0x1588168,
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=1 '\001',
    run_once=<optimized out>, dest=dest@entry=0x1557ad8, altdest=altdest@entry=0x1557ad8,
    completionTag=0x7ffcb8ea2810 "") at pquery.c:773
#15 0x0000000000708790 in exec_execute_message (max_rows=9223372036854775807,
    portal_name=0x15576c8 "") at postgres.c:1984
#16 PostgresMain (argc=<optimized out>, argv=argv@entry=0x14de7f8, dbname=<optimized out>,
    username=<optimized out>) at postgres.c:4151
#17 0x000000000047b8de in BackendRun (port=0x14e6350) at postmaster.c:4405
#18 BackendStartup (port=0x14e6350) at postmaster.c:4077
#19 ServerLoop () at postmaster.c:1755
#20 0x00000000006a2492 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x1477250)
    at postmaster.c:1363
#21 0x000000000047cba5 in main (argc=3, argv=0x1477250) at main.c:228
```

**Comment by pykello** [comment] 2018-04-16 17:48
@onderkalaci Do you get this segfault when running the github query after loading data as instructed at https://www.citusdata.com/blog/2017/01/27/getting-started-with-github-events-data/?

**Comment by marcocitus** [comment] 2018-05-06 10:25
The segfault is gone, so this issue is now essentially a duplicate of #1986.

**Closed by marcocitus** 2018-05-06 10:25 UTC
Labels: bug
