### ISSUE TITLE
DDL commands (Alter Table, Create Index) display Notice messages that may confuse users

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1531] opened 2017-08-01 21:12 UTC
When the user starts up Citus and runs their first DDL command, we display a notice message that informs the user about one-phase commit and asks that they switch to 2PC for extra safety.

We also have old logic in our DDL command propagation to mark shards as invalid in certain scenarios in case the DDL fails on both replicas.

<pre>
postgres=# ALTER TABLE campaigns ADD CONSTRAINT testfk FOREIGN KEY (company_id) REFERENCES companies (id);
NOTICE:  using one-phase commit for distributed DDL commands
HINT:  You can enable two-phase commit for extra safety with: SET citus.multi_shard_commit_protocol TO '2pc'
</pre>

For a new user, this `NOTICE` message may be confusing. We discussed our options for DDL changes earlier (#513) and had the following reservations for removing this message. I think both of these reservations are now historical and mostly invalid.

* We default to 1PC and not display this notice message. The majority of our users relied on statement based replication and they had high shard counts (1K+). This setup increased the likelihood of a failure.
* We default to 2PC and not display this notice message. In previous Citus versions, using 2PC required increasing `max_prepared_transactions` and then restarting the server. This is no longer the case.

**Comment by marcocitus** [comment] 2017-08-25 11:21
Duplicate of #1059

**Closed by marcocitus** 2017-08-25 11:21 UTC
