### ISSUE TITLE
csql broke psql history

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#507] opened 2016-05-07 12:26 UTC
If I use psql then run command in the csql and back to psql I will get broken command history.

```
$ psql -h host -p 9700 db root
psql (9.5.2)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

db# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue |    shardmaxvalue    
--------------+---------+--------------+------------+---------------+---------------------
       104884 |  102008 | f            |            | 0             | 11840
       104884 |  102009 | t            |            | 11841         | 9223372036854775807
       105102 |  102010 | f            |            | 0             | 244607
       105102 |  102011 | t            |            | 244608        | 9223372036854775807
(4 rows)

db# \q
$ csql -h host -p 9700 db root
csql (9.5.2)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

db# asdf;
ERROR:  syntax error at or near "asdf"
LINE 1: asdf;
        ^
db# \q
$ psql -h host -p 9700 db root
psql (9.5.2)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
##### HERE I press <ARROW-UP>
db# select\040*\040from\040pg_dist_shard;
```

as you can see I get \040 characters in place of space.
So after csql usage I need to retype all my commands... ((

**Comment by ozgune** [comment] 2016-05-07 18:09
@KES777 -- thanks for reporting this.

The primary motivation for having csql was to enable the client-side ``\stage`` command. This way, users would be able to bulk load data into distributed tables that are partitioned by ``append``.

We added ``COPY`` support for ``append`` partitioned tables recently (#305); and these changes will be available in 5.2. With these changes, we may be deprecating ``\stage`` and csql. 

I'm assigning this issue to @sumedhpathak -- Sumedh, are we planning to deprecate csql in favor of the COPY changes?

**Comment by anarazel** [comment] 2016-05-08 19:14
On 2016-05-07 11:09:29 -0700, Ozgun Erdogan wrote:
> @KES777 -- thanks for reporting this.
> 
> The primary motivation for having csql was to enable the client-side ``\stage`` command. This way, users would be able to bulk load data into distributed tables that are partitioned by ``append``.

Very likely i this is caused by one version using libedit, the other
libreadline. Unfortunately those aren't compatible.

**Comment by ozgune** [comment] 2016-10-07 17:48
@lithp / @metdos -- When we deprecated ``\stage``, did we remove csql as well?

If we did, could we close this issue?

**Comment by marcocitus** [comment] 2016-10-07 17:49
We did.

**Closed by marcocitus** 2016-10-07 17:49 UTC
