### ISSUE TITLE
Foreign key to reference tables

### ISSUE THREAD

**Issue by Splarv** [citusdata/citus#2036] opened 2018-03-02 12:27 UTC
```
=> create table a (a int primary key);
CREATE TABLE
=> DO $DO$declare begin perform create_reference_table('a');end$DO$;
DO
=> create table b (b int primary key, a int not null references a);
CREATE TABLE
=> DO $DO$declare begin perform create_reference_table('b');end$DO$;
ERROR:  cannot create foreign key constraint from or to reference tables
CONTEXT:  SQL statement "SELECT create_reference_table('b')"
PL/pgSQL function inline_code_block line 1 at PERFORM
```
Here are two issues. First, according to the error message I cannot create foreign key constraint to reference tables, but, as you can see I can. Thus there is the wrong error message or the wrong check constraint. And second, this may be feature request, I can't see any reason to prevent create foreign keys between reference tables.

**Comment by onderkalaci** [comment] 2018-03-02 12:44
> Here are two issues. First, according to the error message I cannot create foreign key constraint to reference tables, but, as you can see I can.

As far as I can see, you get an error in the end? I think the error message misses mentioning about the referencing table being a distributed or a reference table. (e.g., not a local PostgreSQL table).

>  And second, this may be feature request, I can't see any reason to prevent create foreign keys between reference tables.

Sure, #968 seems to be the same issue?

**Comment by ozgune** [comment] 2018-03-08 18:40
Hey @Splarv -- I'm closing this issue as a duplicate of #968.

If you think #968 doesn't cover the issue around foreign keys to reference tables, please reopen this issue.

**Closed by ozgune** 2018-03-08 18:40 UTC
