### ISSUE TITLE
Joining two append tables within a schema causes 'failed to execute job' error

### ISSUE THREAD

**Issue by trifthen** [citusdata/citus#504] opened 2016-05-06 21:30 UTC
Creating a table within a schema seems to work as expected. Selecting from two tables within a schema also works as expected. However upon joining them together, it would appear that citus "forgets" the schema information.

## How to Replicate

```
CREATE SCHEMA foo;

CREATE TABLE foo.bar (id INT, created_dt TIMESTAMPTZ);
CREATE TABLE foo.baz (id INT, created_dt TIMESTAMPTZ);

SELECT master_create_distributed_table(
  'foo.bar', 'id', 'append'
);

SELECT master_create_distributed_table(
  'foo.baz', 'id', 'append'
);

SELECT master_create_empty_shard('foo.bar');
SELECT master_create_empty_shard('foo.baz');
```

## Results

As can be seen below, using the tables normally results in normal operation:

```
SELECT * FROM foo.bar;

 id | created_dt
----+------------
(0 rows)

SELECT * FROM foo.baz;

 id | created_dt
----+------------
(0 rows)
```

However, joining the two tables together is a different story:

```
SELECT count(*)
  FROM foo.bar
  JOIN foo.baz USING (id);

WARNING:  could not receive query results from localhost:6100
WARNING:  could not receive query results from localhost:6101
WARNING:  could not receive query results from localhost:6100
ERROR:  failed to execute job 30
```

Shard logs appear to complain that the shards do not exist, yet do not mention the `foo` schema at all:

```
2016-05-06 16:20:58 CDT [29664-1] postgres@execution ERROR:  relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29664-2] postgres@execution STATEMENT:  COPY baz_102027 TO STDOUT
2016-05-06 16:20:58 CDT [29665-1] postgres@execution WARNING:  could not receive query results from localhost:6100
2016-05-06 16:20:58 CDT [29665-2] postgres@execution DETAIL:  Client error: relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29667-1] postgres@execution ERROR:  relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29667-2] postgres@execution STATEMENT:  COPY baz_102027 TO STDOUT
2016-05-06 16:20:58 CDT [29665-3] postgres@execution WARNING:  could not receive query results from localhost:6101
2016-05-06 16:20:58 CDT [29665-4] postgres@execution DETAIL:  Client error: relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29665-5] postgres@execution ERROR:  could not fetch relation: "baz_102027"
2016-05-06 16:20:58 CDT [29665-6] postgres@execution STATEMENT:  SELECT worker_fetch_regular_table  ('baz_102027', 0, '{localhost,localhost}', '{6100,6101}')
```

**Comment by ozgune** [comment] 2016-05-06 21:52
@trifthen -- thanks for reporting this.

This issue may be a duplicate of #77. Your issue description is more comprehensive, so if these two issues are duplicates, we'll likely close out #77. I'll also add this issue to #122.

**Comment by trifthen** [comment] 2016-05-06 22:02
It looks like the same problem. Thanks for catching that. Sorry for duping. :)

**Comment by onderkalaci** [comment] 2016-05-25 10:26
Verified once more that the issue is valid:

```SQL

CREATE SCHEMA tpch;

CREATE TABLE tpch.nation_append (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));
SELECT master_create_distributed_table('tpch.nation_append', 'n_nationkey', 'append');

\COPY tpch.nation_append FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|'


CREATE TABLE tpch.nation_append_2 (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));
SELECT master_create_distributed_table('tpch.nation_append_2', 'n_nationkey', 'append');

\COPY tpch.nation_append_2 FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|'


SELECT count(*) FROM tpch.nation_append t1, tpch.nation_append_2 t2 WHERE t1.n_name = t2.n_name;
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: could not fetch relation: "nation_append_2_102015"
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: could not fetch relation: "nation_append_2_102015"
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: could not fetch relation: "nation_append_2_102015"
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: could not fetch relation: "nation_append_2_102015"
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: could not fetch relation: "nation_append_2_102015"
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: could not fetch relation: "nation_append_2_102015"
ERROR:  failed to execute job 12
DETAIL:  Failure due to failed task 6

-- worker log
STATEMENT:  SELECT worker_fetch_regular_table  ('nation_append_2_102015', 8192, '{localhost,localhost}', '{9700,9701}')
```

**Comment by onderkalaci** [comment] 2016-05-26 13:42
A more comprehensive tests which includes cross schema joins as well. All the queries below fail

```SQL



CREATE SCHEMA tpch_1;
CREATE SCHEMA tpch_2;


CREATE TABLE nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));



CREATE TABLE tpch_1.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));

CREATE TABLE tpch_1.nation_hash_2 (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));


CREATE TABLE tpch_2.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));


SELECT master_create_distributed_table('public.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('public.nation_hash', 4, 1);
\COPY public.nation_hash FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|';


SELECT master_create_distributed_table('tpch_1.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash', 4, 1);
\COPY tpch_1.nation_hash FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|';

SELECT master_create_distributed_table('tpch_1.nation_hash_2', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash_2', 4, 1);
\COPY tpch_1.nation_hash_2 FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|';


SELECT master_create_distributed_table('tpch_2.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_2.nation_hash', 4, 1);
\COPY tpch_2.nation_hash FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|';


-- fails
SET search_path TO public;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;


-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;

--fails 
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;

-- fails
SET search_path TO public;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_1.nation_hash_2 n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;


-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    nation_hash n1, nation_hash_2 n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;
```

**Comment by onderkalaci** [comment] 2016-05-31 12:40
Similar example with subquery pushdowns where `worker_fetch_regular_table()` fails to fetch table:

```SQL
CREATE SCHEMA tpch_1;


CREATE TABLE tpch_1.lineitem (
    l_orderkey bigint not null,
    l_partkey integer not null,
    l_suppkey integer not null,
    l_linenumber integer not null,
    l_quantity decimal(15, 2) not null,
    l_extendedprice decimal(15, 2) not null,
    l_discount decimal(15, 2) not null,
    l_tax decimal(15, 2) not null,
    l_returnflag char(1) not null,
    l_linestatus char(1) not null,
    l_shipdate date not null,
    l_commitdate date not null,
    l_receiptdate date not null,
    l_shipinstruct char(25) not null,
    l_shipmode char(10) not null,
    l_comment varchar(44) not null,
     PRIMARY KEY(l_orderkey, l_linenumber) );

SELECT master_create_distributed_table('tpch_1.lineitem', 'l_orderkey', 'hash');
SELECT master_create_worker_shards('tpch_1.lineitem', 16, 1);


COPY tpch_1.lineitem FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/lineitem.1.data' with delimiter '|';
COPY tpch_1.lineitem FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/lineitem.2.data' with delimiter '|';



CREATE TABLE tpch_1.orders (
    o_orderkey bigint not null,
    o_custkey integer not null,
    o_orderstatus char(1) not null,
    o_totalprice decimal(15,2) not null,
    o_orderdate date not null,
    o_orderpriority char(15) not null,
    o_clerk char(15) not null,
    o_shippriority integer not null,
    o_comment varchar(79) not null,
    PRIMARY KEY(o_orderkey) );

SELECT master_create_distributed_table('tpch_1.orders', 'o_orderkey', 'hash');
SELECT master_create_worker_shards('tpch_1.orders', 16, 1);


COPY tpch_1.orders FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/orders.1.data' with delimiter '|';
COPY tpch_1.orders FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/orders.2.data' with delimiter '|';

SET citus.subquery TO on;

-- fails
SET search_path TO public;
SELECT
    avg(unit_price)
FROM
    (SELECT
        l_orderkey,
        avg(o_totalprice / l_quantity) AS unit_price
    FROM
        tpch_1.lineitem,
        tpch_1.orders
    WHERE
        l_orderkey = o_orderkey
    GROUP BY
        l_orderkey) AS unit_prices
WHERE
    unit_price > 1000 AND
    unit_price < 10000;

-- fails
SET search_path TO tpch_1;
SELECT
    avg(unit_price)
FROM
    (SELECT
        l_orderkey,
        avg(o_totalprice / l_quantity) AS unit_price
    FROM
        lineitem,
        orders
    WHERE
        l_orderkey = o_orderkey
    GROUP BY
        l_orderkey) AS unit_prices
WHERE
    unit_price > 1000 AND
    unit_price < 10000;

```

Worker logs:

```
ERROR:  could not fetch relation: "orders_102040"
STATEMENT:  SELECT worker_fetch_regular_table  ('orders_102040', 0, '{localhost}', '{9700}')
```

**Closed** 2016-07-22 06:56 UTC
Labels: needs review
