### ISSUE TITLE
Query planner speed for cstore increases linearly with number of shards

### ISSUE THREAD

**Issue by tedkornish** [citusdata/citus#667] opened 2016-07-22 21:00 UTC
I noticed, when testing on a `cstore` table broken into 256 shards, that planner performance was taking up almost the entire time of simpler queries. I did some poking around on running the same query over tables split into different numbers of shards and you can see that time to plan (`EXPLAIN` - not `EXPLAIN ANALYZE`, so this really is planner-only) goes up roughly as a function of number of shards.

I ran the `EXPLAIN` queries a number of times to make sure they were consistent.

| number of shards | time to plan (ms) |
| --- | --- |
| 32 | 205 |
| 64 | 382 |
| 128 | 752 |
| 256 | 1519 |

![screen shot 2016-07-22 at 13 50 10](https://cloud.githubusercontent.com/assets/2671967/17071054/1bf91548-5014-11e6-9517-368445e4bd23.png)

![screen shot 2016-07-22 at 13 48 07](https://cloud.githubusercontent.com/assets/2671967/17071062/22d03982-5014-11e6-96f3-25994f48de42.png)

![screen shot 2016-07-22 at 13 49 24](https://cloud.githubusercontent.com/assets/2671967/17071064/289b7a8e-5014-11e6-9b48-118d626bd310.png)

![screen shot 2016-07-22 at 13 23 15](https://cloud.githubusercontent.com/assets/2671967/17071073/2f8ade5c-5014-11e6-881e-a080f8c94f10.png)

**Comment by anarazel** [comment] 2016-07-22 21:06
> I noticed, when testing on a `cstore` table broken into 256 shards, that planner performance was taking up almost the entire time of simpler queries. I did some poking around on running the same query over tables split into different numbers of shards and you can see that time to plan (`EXPLAIN` - not `EXPLAIN ANALYZE`, so this really is planner-only) goes up roughly as a function of number of shards.
> 
> I ran the `EXPLAIN` queries a number of times to make sure they were consistent.
> 
> | number of shards | time to plan (ms) |
> | --------------- | ---------- |
> | 32 | 205 |
> | 64 | 382 |
> | 128 | 752 |
> | 256 | 1519 |

It might be worthwhile to evaluate this with master, we've done some
improvements there.  If not improved, could you please provide a recipe
to reproduce the planner performance issue? That way, if we have a fix,
we can actually evaluate whether it fixes things for you.

**Comment by tedkornish** [comment] 2016-07-22 21:12
@anarazel - thanks for the fast reply. Will test with the nightly build and get back to you.

**Comment by ozgune** [comment] 2016-07-23 17:26
@samay-sharma and @tedkornish have been looking into reproducing this issue. I just wanted to copy/paste a quick update for the Citus team. We'll continue investigating next week.

--

@samay-sharma: I tried to reproduce this with master (i.e. 5.1-5) for both cstore and non-cstore tables and for me the planning time was around 25-35ms. I tried with 128 shards and hash distribution. I did try with a simple schema; adding DDLs and explain plans below.

<pre>
create foreign table t1_cstore (c1 int) server cstore_server options (compression 'pglz'); 
select * from master_create_distributed_table('t1_cstore', 'c1', 'hash');                    
select * from master_create_worker_shards('t1_cstore', 128, 1); 
</pre>

<pre>
postgres=# explain select count(*) from t1_cstore;
                                                   QUERY PLAN                                                   
----------------------------------------------------------------------------------------------------------------
 Distributed Query into pg_merge_job_0135
   Executor: Real-Time
   Task Count: 128
   Tasks Shown: One of 128
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Aggregate  (cost=0.00..0.01 rows=1 width=0)
               ->  Foreign Scan on t1_cstore_102617 t1_cstore  (cost=0.00..0.00 rows=1 width=0)
                     CStore File: /Users/samaysharma/Work/install_postgres95/./data.9700/cstore_fdw/12641/52298
                     CStore File Size: 0
 Master Query
   ->  Aggregate  (cost=0.00..0.02 rows=1 width=0)
         ->  Seq Scan on pg_merge_job_0135  (cost=0.00..0.00 rows=0 width=0)
(13 rows)
​
Time: 26.164 ms
postgres=# explain select count(*) from t1;
                                    QUERY PLAN                                    
----------------------------------------------------------------------------------
 Distributed Query into pg_merge_job_0136
   Executor: Real-Time
   Task Count: 128
   Tasks Shown: One of 128
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Aggregate  (cost=41.88..41.88 rows=1 width=0)
               ->  Seq Scan on t1_102233 t1  (cost=0.00..35.50 rows=2550 width=0)
 Master Query
   ->  Aggregate  (cost=0.00..0.02 rows=1 width=0)
         ->  Seq Scan on pg_merge_job_0136  (cost=0.00..0.00 rows=0 width=0)
(11 rows)
​
Time: 32.736 ms
</pre>

**Comment by tedkornish** [comment] 2016-07-23 18:31
I realize now that I omitted a very important detail: the table in question is upwards of 1400 columns wide, since it represents a denormalized set of transactional tables. I tested a narrow cstore table and found no query planner slowdown, but when testing on a very wide table, saw the expected linear increase in times.

Here's a script which you can run which should give expected slowdown. For me, planning the `COUNT(*)` query takes about 1.5sec.

[cstore_example.sql.zip](https://github.com/citusdata/citus/files/379920/cstore_example.sql.zip)

**Comment by tedkornish** [comment] 2016-07-23 19:06
Another data point: I tweaked the above script to make a vanilla Postgres table instead of a cstore foreign table, and it looks like the planner still exhibits slow times. For a non-cstore table:

```
                                           QUERY PLAN
------------------------------------------------------------------------------------------------
 Distributed Query into pg_merge_job_6356
   Executor: Real-Time
   Task Count: 256
   Tasks Shown: One of 256
   ->  Task
         Node: host=ec2-54-149-153-15.us-west-2.compute.amazonaws.com port=5432 dbname=postgres
         ->  Aggregate  (cost=10.00..10.01 rows=1 width=0)
               ->  Seq Scan on users_107964 users  (cost=0.00..10.00 rows=1 width=0)
 Master Query
   ->  Aggregate  (cost=0.00..0.02 rows=1 width=0)
         ->  Seq Scan on pg_merge_job_6356  (cost=0.00..0.00 rows=0 width=0)
(11 rows)

Time: 1537.444 ms
```

I also tested planning time for non-distributed cstore and vanilla Postgres tables with the same number of columns.

```
                         QUERY PLAN
------------------------------------------------------------
 Aggregate  (cost=10.00..10.01 rows=1 width=0)
   ->  Seq Scan on users  (cost=0.00..10.00 rows=1 width=0)
(2 rows)

Time: 6.249 ms

                                QUERY PLAN
--------------------------------------------------------------------------
 Aggregate  (cost=0.00..0.01 rows=1 width=0)
   ->  Foreign Scan on users  (cost=0.00..0.00 rows=1 width=0)
         CStore File: /var/lib/postgresql/9.5/main/cstore_fdw/12379/69563
         CStore File Size: 0
(4 rows)

Time: 6.092 ms
```

Since those were fast, the bug appears to be in Citus' query planning for wide, distributed tables.

**Comment by ozgune** [comment] 2016-07-25 17:35
@tedkornish -- thanks for the comprehensive notes. We're looking into this and will provide an update on the issue within the next 1-2 days.

**Comment by ozgune** [comment] 2016-07-26 18:28
@tedkornish -- We have a working theory for the underlying issue. When planning a query for distributed execution, we copy target lists (columns) multiple times. With large number of columns, this causes a performance problem.

We'll do fewer copy operations with the upcoming APIs available in PostgreSQL 9.6. We'll also performance profile your example, identify specific bottlenecks, and post an update in a few days.

In the mean time, @onderkalaci ran some performance numbers with varying column counts in a different context. @onderkalaci -- if you have any observations that relate to this issue, could you chime in?

**Comment by saicitus** [comment] 2016-07-27 17:34
@tedkornish, @ozgune 
I could reproduce this issue (@tedkornish - Thanks for the script 👍 ). This is not specific to cstore tables, rather it arises with any table with large number(ex. >1000) of columns. I did some profiling using perf and here are some observations: 

When a distributed query is planned, for each shard the planner does a check on each column(of the shard) whether the column name is unique or not, and if a name is not unique it creates an alias name(which is used in the later stages of planning) for that column. This check involves a nested loop iteration in which for each column there is a uniqueness check with all the other columns. In short it is an order of n-squared operation, where n is the number of columns. This happens for all the shards. So hence when the number columns are large, there is a noticeable linear increase of the query planning time with the increase in the number of shards.

The above stated planning logic(for checking column uniqueness) is borrowed from PostgreSQL source, and the good news is that in the upcoming PostgreSQL 9.6, the nested loop iteration would be prevented by using a hash table. I guess that this would significantly improve the query planning time.

Hope the above analysis helps.

@anarazel : If you have some inputs/comments, Could you please chime in?

**Comment by anarazel** [comment] 2016-07-27 17:59
It's not really the planner that does these checks, it's done when deparsing the queries issued to the workers. 

Unfortunately it's only a related thing that was fixed in 9.6, not precisely what's needed (the equivalent case for many relations, but not the one for many columns was fixed).  For normal postgres this unlikely to ever be as much of a problem, because the number of columns is limited to ~1600, and nothing queries columns at a  high frequency there.

**Comment by saicitus** [comment] 2016-07-27 22:55
The following are the screenshots of perf output:

**colname_is_unique** 
![is_column_unique](https://cloud.githubusercontent.com/assets/18174230/17195352/0673999e-5412-11e6-9717-5f5938f20713.png)

**strcmp calleb by colname_is_unique**
![screen shot 2016-07-27 at 3 43 19 pm](https://cloud.githubusercontent.com/assets/18174230/17195370/28483368-5412-11e6-9d84-b3fb871c5ccb.png)
The call graph can be gauged by reading the perf output bottom->top.

**Comment by anarazel** [comment] 2016-07-27 23:00
Note that the top symbol, with the 67%, is libc functionality, called by
colname_is_unique().

**Comment by serprex** [comment] 2019-11-07 23:23
Issue name is non descriptive of the root of the issue being postgresql deparsing speed for many columns. If this an issue, it should be opened as a patch to postgres to do something like use a bloom filter when column count exceeds something like 500

**Closed by serprex** 2019-11-07 23:23 UTC
Labels: priority:high
