### ISSUE TITLE
ERROR: invalid attnum -1 for rangetable entry XXX

### ISSUE THREAD

**Issue by trntv** [citusdata/citus#512] opened 2016-05-10 07:27 UTC
Hi guys, first of all, thank you for your great job!

I don't really know if it citus or postgres related problem, but it happens on distributed tables only

Table schema:

```
CREATE TABLE events
(
    uuid UUID,
    step VARCHAR(1024),
    substep VARCHAR(1024),
    message jsonb,
    xstring VARCHAR(64),
    xstring_data JSONB,
    version VARCHAR(64),
    product_id VARCHAR(255),
    company_id VARCHAR(255),
    tid VARCHAR(200),
    adv_type VARCHAR(32),
    ip VARCHAR(15),
    timestamp TIMESTAMP
);
SELECT master_create_distributed_table('events', 'uuid', 'hash');
```

Query:

```
SELECT *, CTID FROM postgres.public.events events
```

Result:

```
ERROR:  invalid attnum -1 for rangetable entry events
```

**Comment by mtuncer** [comment] 2016-05-10 08:14
Heu @trntv 

This is caused by ctid not having an expected varattno value. It could only be detected by vartype attribute being TIDOID.

I am not sure if CTID has any value in distributed tables, postgresql documentation says it is useless for long term row identifier [here](http://www.postgresql.org/docs/9.5/static/ddl-system-columns.html).

Perhaps we should just reject this query with a better error message. 

Note : This behavior is not observed for router plannable queries i.e. queries like ```SELECT *, CTID FROM postgres.public.events events where uuid = '9deab30e-732c-0a5f-1df8-ff2f4e4787f7' ``` works fine.

**Comment by trntv** [comment] 2016-05-11 11:02
@mtuncer, thank you for the answer

> Perhaps we should just reject this query with a better error message.

It may be a solution, but some software (DataGrip in my case) generates such queries behind the scenes. And there is nothing we can do to disable such behavior.

BTW, there is exact same problem with "having" queries in Tableau

**Comment by michelp** [comment] 2016-06-22 22:12
The Postico OSX native client also generates a query that orders by ctid when users click on a table in the interface presumably to show the user a "stable" view every time they click a table.  This makes the client unusable with citus.  I've made an issue on postico's tracker:

https://github.com/jakob/Postico/issues/234

**Comment by jakob** [comment] 2016-08-03 15:08
Are you planning to fix this? Will future versions of Citus allow querying the `ctid` column?

If not, do you have any good ideas how I can detect that querying `ctid` is not allowed?

**Comment by michelp** [comment] 2016-08-03 17:15
@jakob I don't work at citus and can't speak for them, but if you don't mind me asking, what is the purpose of default ordering by ctid in postico?

**Comment by jakob** [comment] 2016-08-04 05:52
@michelp As mentioned in https://github.com/jakob/Postico/issues/234, the purpose of ordering by ctid is to make sure that when you click "next page", you actually see the next page. It's used only when the table has no primary key.

I also use the ctid column when updating rows in tables without a primary key. The ctid lets me guarantee that an update affects only a single row, even when there are multiple identical rows in a table.

**Comment by ozgune** [comment] 2016-08-19 17:28
@trntv -- We're looking into how long it would take to fix this issue. For now, it isn't prioritized for our v5.3 release.

I also had a quick question. When you mention that this is the same issue with Tableau's ``HAVING`` clause, do you mean that Tableau sends queries with the ``HAVING`` clause and Citus doesn't support them? Or is this issue related to DataGrip?

@jakob -- Do @lfittl's comments help in the meantime?

**Comment by ozgune** [comment] 2016-08-24 20:48
+1 -- This issue came up in a recent private Slack conversation as well in the context of DataGrip integration.

**Comment by trntv** [comment] 2016-08-25 15:19
> I also had a quick question. When you mention that this is the same issue with Tableau's HAVING clause, do you mean that Tableau sends queries with the HAVING clause and Citus doesn't support them?

Yes, Tableau generates queries with `HAVING` clause

**Comment by ozgune** [comment] 2016-10-07 17:45
@trntv -- I wanted to drop a quick update on the ``HAVING`` clause. We prioritized this feature (#787) for our upcoming release.

**Comment by ozgune** [comment] 2016-10-13 16:49
@trntv, @michelp, @jakob -- This issue should now be fixed in master (scheduled for v6.0). We made changes as part of #581 (pull request: #773) and should now support ctids.

**If** you're building from source, could you check if this issue is resolved for you?

**Comment by jasonmp85** [comment] 2016-10-13 17:25
(FWIW I just built master from source and ran a query using `ctid` without problems)

**Comment by anarazel** [comment] 2016-10-13 18:00
On 2016-10-13 10:25:33 -0700, Jason Petersen wrote:
> (FWIW I just built master from source and ran a query using `ctid` without problems)

We also have a regression test verifying that.

**Comment by ozgune** [comment] 2016-11-02 21:16
@jasonmp85 -- are we then good to close this issue?

**Comment by jasonmp85** [comment] 2016-11-02 23:16
I'd say yes. Closing.

**Closed by jasonmp85** 2016-11-02 23:16 UTC
Labels: bug, usability
