### ISSUE TITLE
If we stage shards with replication factor 2, and then set the replication factor back to 1, greedy task assignment algorithm ignores the second shard placements of the previous shards.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#63] opened 2016-02-02 23:44 UTC
If we stage shards with replication factor 2, and then set the replication factor back to 1, greedy task assignment algorithm ignores the second shard placements of the previous shards.

**Comment by marcocitus** [comment] 2018-07-21 12:39
Kind of a duplicate of #198

**Closed by marcocitus** 2018-07-21 12:39 UTC
