### ISSUE TITLE
Adding support for INHERIT and SET for Grant Role for Postgres 16

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/citus#7155] opened 2023-08-28 15:06 UTC
In Postgres 16, INHERIT and SET options are introducted in addition to ADMIN for Grant and Revoke Role. Right now, only ADMIN is being supported.
All of the options should be supported
Here, the Grant and Revoke statement options

```SQL
GRANT role_name [, ...] TO role_specification [, ...]
    [ WITH { ADMIN | INHERIT | SET } { OPTION | TRUE | FALSE } ]
    [ GRANTED BY role_specification ]

REVOKE [ { ADMIN | INHERIT | SET } OPTION FOR ]
    role_name [, ...] FROM role_specification [, ...]
    [ GRANTED BY role_specification ]
    [ CASCADE | RESTRICT ]
```
https://www.postgresql.org/docs/16/sql-grant.html
https://www.postgresql.org/docs/16/sql-revoke.html

Code Place to add this checks:
https://github.com/citusdata/citus/blob/add596cd2b9a0fe0eb79e8010fa9c16c974cc6f1/src/backend/distributed/deparser/deparse_role_stmts.c#L360

**Comment by JelteF** [comment] 2023-08-28 15:14
Closing since it's a duplicate of #7148

**Closed by JelteF** 2023-08-28 15:14 UTC

**Comment by naisila** [comment] 2023-08-29 07:14
@gurkanindibay if you run into other PG16 stuff, it would be nice to add them to this general issue https://github.com/citusdata/citus/issues/7138
