### ISSUE TITLE
Casting varchar to timestamp does not work in a query on a distributed table

### ISSUE THREAD

**Issue by sbarlabanov** [citusdata/citus#5646] opened 2022-01-22 19:17 UTC
While migrating from a standard PostgreSQL DB to one powered by Citus we discovered some prepared statements stopped working with the error message: `ERROR:  cannot cast type cstring to timestamp without time zone`. Same statements work on a normal Postgres instance and they also work agains a local table on Citus. But they do not work on a distributed table. Steps to reproduce:

```sql
CREATE TABLE data
(
    local_time       TIMESTAMP                NOT NULL,
    id               INT4                     NOT NULL,
    value            FLOAT8                   NOT NULL
);

PREPARE test (varchar) AS
    SELECT * FROM data d WHERE d.local_time > cast($1 as timestamp(6) without time zone);
	
EXECUTE test('2008-04-07 00:00:00'); -- works - returns 0 rows	

-- Now do:

SELECT create_distributed_table(table_name := 'data', distribution_column := 'id', shard_count:= 2);

EXECUTE test('2008-04-07 00:00:00'); -- does not work - ERROR:  cannot cast type cstring to timestamp without time zone
```

In the server log we see:

```
2022-01-22 18:47:05.130 UTC [12817] ERROR:  cannot cast type cstring to timestamp without time zone at character 129
2022-01-22 18:47:05.130 UTC [12817] STATEMENT:  SELECT local_time, id, value FROM public.data_102012 d WHERE (local_time OPERATOR(pg_catalog.>) ('2008-04-07 00:00:00'::cstring)::timestamp(6) without time zone)
```

Looks like the query has been rewritten with `::cstring` cast appended. `cstring` does not look correct. 

P.S. just discovered while finishing writing the ticket: seems that the problem has nothing to do with the prepared statement mechanism: issuing the query `SELECT * FROM data d WHERE d.local_time > cast('2008-04-07 00:00:00'::varchar as timestamp(6) without time zone);` does not work when the table is distributed.

Tested on Postgres 13 and 14 with Citus 10.2.

**Comment by onurctirtir** [comment] 2022-01-24 08:11
Thank you for reporting the issue, I was able to reproduce on master too;
```sql
CREATE TABLE data
(
    local_time       TIMESTAMP                NOT NULL,
    id               INT4                     NOT NULL,
    value            FLOAT8                   NOT NULL
);
select create_distributed_table ('data', 'id');

set citus.log_remote_commands to on;

SELECT * FROM data d WHERE d.local_time > cast('2008-04-07 00:00:00'::varchar as timestamp(6) without time zone);
NOTICE:  issuing SELECT local_time, id, value FROM public.data_102040 d WHERE (local_time OPERATOR(pg_catalog.>) ('2008-04-07 00:00:00'::cstring)::timestamp(6) without time zone)
DETAIL:  on server onurctirtir@localhost:10700 connectionId: 16
ERROR:  cannot cast type cstring to timestamp without time zone
CONTEXT:  while executing command on localhost:10700
```

A quick workaround seems to be removing `::varchar` cast from the query, but currently looking into that to understand why this happens.

**Comment by naisila** [comment] 2022-09-29 13:54
#6061 is a duplicate of this issue. Same problem occurring with text instead of varchar.

**Comment by naisila** [comment] 2022-09-30 09:44
Workaround: prepare the statement such that the casting is done before sending the distributed queries:

```SQL
PREPARE test (varchar) AS
  WITH specific_time AS (SELECT cast($1 as timestamp(6) without time zone))
  SELECT * FROM data d WHERE d.local_time > (SELECT * FROM specific_time);
```

**Closed** 2023-05-04 13:46 UTC
Labels: bug, user_reported
