### ISSUE TITLE
Citus may not behave properly on the first command execution after a worker is stopped

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#1926] opened 2018-01-03 13:38 UTC
In a hash distributed table, I manually stopped one of the workers that the below query would hit. I was expecting it to return an error message but it returned me empty results. The steps to reproduce the issue is below.

```SQL
create table test_2(a int, b int);
select create_distributed_table('test_2', 'a');
insert into test_2 SELECT x%307, x%1001 FROM generate_series(1,30000) as f(x);

select * from test_2 where test_2.a=100;

  a  |  b
-----+-----
 100 | 100
 100 | 407
 100 | 714
 100 |  20
 100 | 327
 100 | 634
 100 | 941
 100 | 247
 100 | 554
 100 | 861
 100 | 167
 100 | 474
 100 | 781
...
-- continues

SELECT get_shard_id_for_distribution_column('test_2', 100);
 get_shard_id_for_distribution_column
--------------------------------------
                               102376
```
I checked in which worker the shard is located in and killed it manually by the following command
```
pg_ctl -D DBw1 -l logfile stop -m i
```
After that I run the router select query again
```SQL
postgres=# select * from test_2 where test_2.a=100;
 a | b
---+---
(0 rows)
```

I doubt that this issue might be related to cache invalidation because when we run the same query again, citus gives a connection error as expected.
```SQL
postgres=# select * from test_2 where test_2.a=100;
WARNING:  01000: connection error: localhost:9701
DETAIL:  server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
could not send SSL negotiation packet: Broken pipe
LOCATION:  ReportConnectionError, remote_commands.c:247
ERROR:  XX000: could not receive query results
LOCATION:  ExecuteSingleSelectTask, multi_router_executor.c:657
Time: 2.116 ms
```

**Comment by onderkalaci** [comment] 2018-01-03 13:42
I cannot reproduce this. I got errors as expected (w/wout triggering cache invalidations):
```
select * from test_2 where test_2.a=100;
WARNING:  connection error: localhost:9701
DETAIL:  could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 9701?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 9701?
ERROR:  could not receive query results
```

**Comment by furkansahin** [comment] 2018-01-03 14:37
The issue is reproducible when we use 

`pg_ctl -D DBw1 -l logfile stop -m i`

The immediate mode is the game changer here

**Comment by onderkalaci** [comment] 2018-01-03 15:16
> The issue is reproducible when we use

That's true. It looks like we can reproduce this when the worker is stopped with ` stop -m i` and not with ` stop -m f`. So, my above comment is wrong.

Basically, we're not checking the status of the connection in `StoreQueryResult()`, thus we deduct that no rows returned from the worker.

This doesn't happen on the second call since we're checking the connection status before we come to  `StoreQueryResult()`.

We should probably check that we don't do the same in real-time executor and/or modification queries.

**Comment by onderkalaci** [comment] 2018-01-04 14:01
### Rephrase the issue

Before diving into the details, I'd like to remind that this issue and the following examples only happens:

* Run a command 
* Stop a worker with `m -i` mode  (i.e., `immediate mode`)
* Running the command again for the first time leads to weird issue (**Note: For the second time we run the query, Citus behaves properly**). 

Thus, the issue seems not a super critical issue.

### Summary of affected parts

The good news is that I cannot reproduce this on Citus Cloud, which seems to be prevented via pgbouncer.

The bad news is that, we can reproduce the same issue with many different code-paths in Citus. Some of those ends up with harmful results, some not.

### Details of affected parts

**1. Router Selects**: As explained by @furkansahin in the issue description.

**2. Explain**: Follow the same steps, we'd end up with a crash
```SQL
 EXPLAIN select * from test_2 where test_2.a=100 LIMIT 1;
                                       QUERY PLAN                                        
-----------------------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9701 dbname=postgres
         ->  Limit  (cost=0.00..0.18 rows=1 width=8)
               ->  Seq Scan on test_2_102090 test_2  (cost=0.00..30.96 rows=176 width=8)
                     Filter: (a = 100)
```

```
# stop the worker
pg_ctl -D DBw1 -l logfile stop -m i
```
```SQL
-- re-run the command
postgres=# EXPLAIN select * from test_2 where test_2.a=100 LIMIT 1;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

**3. 2PC recovery errors out unexpectedly:** This should have only been a warning
```SQL
SELECT recover_prepared_transactions();
 recover_prepared_transactions 
-------------------------------
                             0
```
```
# stop the worker
pg_ctl -D DBw1 -l logfile stop -m i
```
```SQL
-- re-run the command
 SELECT recover_prepared_transactions();
ERROR:  server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
CONTEXT:  while executing command on localhost:9701
```

**4. Real-time selects give meaningless warnings when executed in transactions:** We normally don't give these warnings
```SQL
BEGIN;
select * from test_2 where test_2.a!=100 LIMIT 1;
```

```
-- stop the worker
pg_ctl -D DBw1 -l logfile stop -m i
```

```SQL
-- re-run the command
 select * from test_2 where test_2.a!=100 LIMIT 1;
WARNING:  could not consume data from worker node
WARNING:  could not consume data from worker node
WARNING:  could not consume data from worker node
....
```

**5. Probably many other places:** We should investigate many places in Citus code that uses `GetRemoteCommandResult()`

### Root cause of the issue

In many places, we call `GetRemoteCommandResult()` and interpret the result without checking the status of the connection. If the remote connection is closed externally (i.e., worker stopped), `GetRemoteCommandResult()` silently returns `NULL` and Citus interprets that as if all the necessary data is fetched from the connection and we're done with the command.

### My take on the fix

Considering the following:

* We're on the code freeze
* The fix seems to be touching/affecting many places 
* The issue seems not super critical
* The issue exists from 6.2+ to now

I'd suggest handling the issue in the next release cycle with a better understanding.

**Comment by lithp** [comment] 2018-01-10 21:38
This bug came up again while I was doing failure testing on citus-windows: #1942 

I disagree that this bug is not critical. If, in the middle of your query, the remote end closes the connection, Citus returns incorrect results. It doesn't get much worse than that!

**Comment by onderkalaci** [comment] 2018-01-11 08:05
> I disagree that this bug is not critical.

Wait, I also think that this is critical. But, my concerns today are (i) We're on the code freeze, planning to release in 2-3 days (ii) The fix seems to be touching/affecting many places (i.e., the function is called 34 times) (iii) The issue exists from 6.2+ to now

So, seems like better to handle it in the next release with a better understanding. I already brought this issue to @ozgune for the next release, he also agreed that should be fixed.

**Comment by marcocitus** [comment] 2018-01-26 19:04
This issue also causes some "could not modify any active placements" errors for customers, which are unexpected for replication factor 1.

**Comment by jasonmp85** [comment] 2018-01-29 21:52
Yeah, it's not just "when we use the immediate mode for shutdown", it's more that the immediate mode emulates yanking the network cable/shutting down the VM, etc.… this should be handled soon, IMO.

**Closed** 2018-03-02 07:04 UTC
Labels: backport, bug, needs review, priority:high

**Comment by jasonmp85** [comment] 2018-10-02 04:02
@onderkalaci, in _2PC recovery errors out unexpectedly_, do you remember why you said it should only be a warning? If recovery can't contact a node, I don't see why that would be a warning…

**Comment by marcocitus** [comment] 2018-10-02 07:01
We want to recover as much as possible, so we should only throw a warning and continue with the other nodes.
