### ISSUE TITLE
drop table with sequence locked

### ISSUE THREAD

**Issue by tqyq** [citusdata/citus#1601] opened 2017-08-19 08:33 UTC
steps:

1. create table ts (id serial);
2. drop table ts cascade;

the client locked.

version:

citus 6.1, 6.2

**Comment by mtuncer** [comment] 2017-08-21 08:12
Hey @tqyq 

Thanks for the report. These steps does not include a distributed table.  It is creation and drop of a regular table. Citus should not be involved on those operations.

Can you confirm that they are all needed to reproduce the issue ?

thanks

**Comment by marcocitus** [comment] 2017-08-25 10:51
May be a duplicate of https://github.com/citusdata/citus/issues/1269

**Comment by ozgune** [comment] 2017-09-29 22:58
@tqyq - I ran these two steps on Citus 7.0-15 and couldn't reproduce the issue.

Were these the only two commands you ran? Could you provide us more info?

**Comment by marcocitus** [comment] 2017-09-29 23:01
This is an issue when the coordinator is added as a node.

**Comment by ozgune** [comment] 2017-09-29 23:27
Got it. Should we then close this issue as a duplicate of #1269?

**Comment by jasonmp85** [comment] 2017-10-20 19:37
@ozgune I believe so. Closing as we couldn't reproduce, don't have further info, and believe this is a duplicate.

**Closed by jasonmp85** 2017-10-20 19:37 UTC
