### ISSUE TITLE
Citus Query Planner is unable to handle 1=0 conditions

### ISSUE THREAD

**Issue by geraldcm** [citusdata/citus#1230] opened 2017-02-13 22:10 UTC
Citus version: 6.0-17

`explain  DELETE FROM "my_model" WHERE "my_model"."my_shard_key" = 27;
```
                                                          QUERY PLAN

Distributed Query
   Executor: Router
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=ec2-host.compute-1.amazonaws.com   port=5432 dbname=citus
         ->  Delete on my_model_102737  (cost=4.20..13.67 rows=6 width=6)
               ->  Bitmap Heap Scan on my_model_102737  (cost=4.20..13.67 rows=6 width=6)
                     Recheck Cond: (my_shard_key = 27)
                     ->  Bitmap Index Scan on index_my_model_on_shard_key_102737  (cost=0.00..4.20 rows=6 width=0)
                           Index Cond: (my_shard_key = 27)
```
(11 rows)

`explain  DELETE FROM "my_model" WHERE "my_model"."my_shard_key" = 27 and 1=0;`
`ERROR:  distributed modifications must target exactly one shard`

Adding 1=0 makes the query planner unable to see that it has a valid shard_key.

Unfortunately 1=0 is weird byproduct of rails ActiveRecord code when trying to:
`MyModel.where(id: []).delete_all`, 
so ideally this could be a no-op.

**Comment by ozgune** [comment] 2017-02-13 22:46
@marcocitus, @anarazel, @mtuncer -- I remember we fixed an issue related to this on the ``SELECT`` path (#804), and we're now observing it on the ``DELETE`` side.

Do you know how long the fix for this take?

**Comment by anarazel** [comment] 2017-02-13 23:01
Hi Ozgun,

On 2017-02-13 14:46:43 -0800, Ozgun Erdogan wrote:
> @marcocitus, @anarazel, @mtuncer -- I remember we fixed an issue related to this on the ``SELECT`` path (#804), and we're now observing it on the ``DELETE`` side.

That was a different kind of bug though.  Here the issue isn't that we
crash or prune incorrectly, but that we have an error check saying that
something pruned down to 0 shards is invalid for modifications.  Note
that the handling for situation for SELECT queries isn't pretty at all,
we generate a "pseudo query" that doesn't do anything, but is executed
on the remote side...


> Do you know how long the fix for this take?

I think it should be fairly simple in 6.2 (after the temp table changes
- we right now create tupleDescs from the worker query in the router
case, important at least for RETURNING).  Before I'd say it's a bit more
complicated, but also not very hard.  After we basically just remove a
few error checks, and allow for a router queries without a remote query.

Regards,

Andres

**Comment by mtuncer** [comment] 2017-07-03 15:35
your changes on #1474 should also resolve this

**Closed** 2017-08-07 13:48 UTC
Labels: bug
