### ISSUE TITLE
Suspicious regression test failure on CI

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#3581] opened 2020-03-06 12:25 UTC
This is the link to the failure: https://app.circleci.com/jobs/github/citusdata/citus-enterprise/16275

The following is the query/failure:

```SQL
    
WITH fist_table_cte AS
  (SELECT * FROM test_table)
INSERT INTO test_table
            (key, value)
            SELECT
              key, value
            FROM
              fist_table_cte;

 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960000 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_109370671166_from_1960000_to_0}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960001 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_109370671166_from_1960001_to_1}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960002 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_109370671166_from_1960002_to_2}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960003 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_109370671166_from_1960003_to_3}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
+ERROR:  could not find valid entry for shard 140555598973355
```

It might be CTE inlining/processing and/or INSERT..SELECT repartitioning

**Comment by onderkalaci** [comment] 2020-03-09 16:40
Another weird error, the intersection with the above is re-partitioning. Could we have a bug in that code-path?
https://app.circleci.com/jobs/github/citusdata/citus/101067

```SQL
EXPLAIN (COSTS FALSE, FORMAT XML)
 	SELECT count(*)
 	FROM lineitem, orders, customer_append, supplier_single_shard
 	WHERE l_orderkey = o_orderkey
 	AND o_custkey = c_custkey
 	AND l_suppkey = s_suppkey;
-<explain xmlns="http://www.postgresql.org/2009/explain">
-  <Query>
-    <Plan>
-      <Node-Type>Aggregate</Node-Type>
-      <Strategy>Plain</Strategy>
-      <Partial-Mode>Simple</Partial-Mode>
-      <Parallel-Aware>false</Parallel-Aware>
-      <Plans>
-        <Plan>
-          <Node-Type>Custom Scan</Node-Type>
-          <Parent-Relationship>Outer</Parent-Relationship>
-          <Custom-Plan-Provider>Citus Task-Tracker</Custom-Plan-Provider>
-          <Parallel-Aware>false</Parallel-Aware>
-          <Distributed-Query>
-            <Job>
-              <Task-Count>1</Task-Count>
-              <Tasks-Shown>None, not supported for re-partition queries</Tasks-Shown>
-              <Dependent-Jobs>
-                <MapMergeJob>
-                  <Map-Task-Count>1</Map-Task-Count>
-                  <Merge-Task-Count>1</Merge-Task-Count>
-                  <Dependent-Jobs>
-                    <MapMergeJob>
-                      <Map-Task-Count>2</Map-Task-Count>
-                      <Merge-Task-Count>1</Merge-Task-Count>
-                    </MapMergeJob>
-                  </Dependent-Jobs>
-                </MapMergeJob>
-              </Dependent-Jobs>
-            </Job>
-          </Distributed-Query>
-        </Plan>
-      </Plans>
-    </Plan>
-  </Query>
-</explain>
+ERROR:  relation with OID 1983520817 does not exist
```

**Comment by pykello** [comment] 2020-03-09 19:53
> Another weird error, the intersection with the above is re-partitioning. Could we have a bug in that code-path?

They don't use the same code path as far as I know. INSERT/SELECT with repartitioning use a new set of functions.

**Comment by pykello** [comment] 2020-03-09 23:35
Status: still looking into this

1. Could not find any unexpected errors in valgrind report
2. We used to have some "int32 shardId" mistakes until 2 weeks ago, this test case doesn't use any of those code paths, so unlikely to be caused by that.
3. I couldn't find any wrong-doing in the task creation. relationShardList and anchorShardId are being assigned properly.
4. Analyzed paths ending to LookupShardCacheEntry to see if I can spot anything suspicious, nothing found yet.

I think I am going to add some print backtrace code before the "could not find valid entry for shard" error, and repeat the CI until we hit the error again.

**Comment by onderkalaci** [comment] 2020-03-10 07:09
> I think I am going to add some backtrace logging code before the "could not find valid entry for shard" error, and repeat the CI until we hit the error again.

This makes a lot of sense

**Comment by serprex** [comment] 2020-03-27 21:27
Sighted yesterday, so hasn't been fixed: https://app.circleci.com/pipelines/github/citusdata/citus/7639/workflows/b917ad67-5f1a-4c42-a9e6-d49d28704159/jobs/107777

**Comment by onderkalaci** [comment] 2020-03-30 09:00
Another incidence on the same query: https://app.circleci.com/pipelines/github/citusdata/citus/7717/workflows/2a9d7e5b-12b9-4fff-86a0-644da4b5598c/jobs/109117

**Comment by onderkalaci** [comment] 2020-03-30 09:16
Even more interesting example, see the deparsed shared name: `test_table_8531344307640482336`:
```SQL
 DEBUG:  CTE fist_table_cte is going to be inlined via distributed planning
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960000 AS citus_table_alias (key, value) SELECT key, value FROM (SELECT test_table.key, test_table.value, test_table.other_value FROM cte_inline.test_table_1960000 test_table) fist_table_cte WHERE ((worker_hash(key) OPERATOR(pg_catalog.>=) '-2147483648'::integer) AND (worker_hash(key) OPERATOR(pg_catalog.<=) '-1073741825'::integer))
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960001 AS citus_table_alias (key, value) SELECT key, value FROM (SELECT test_table.key, test_table.value, test_table.other_value FROM cte_inline.test_table_1960001 test_table) fist_table_cte WHERE ((worker_hash(key) OPERATOR(pg_catalog.>=) '-1073741824'::integer) AND (worker_hash(key) OPERATOR(pg_catalog.<=) '-1'::integer))
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960002 AS citus_table_alias (key, value) SELECT key, value FROM (SELECT test_table.key, test_table.value, test_table.other_value FROM cte_inline.test_table_1960002 test_table) fist_table_cte WHERE ((worker_hash(key) OPERATOR(pg_catalog.>=) 0) AND (worker_hash(key) OPERATOR(pg_catalog.<=) 1073741823))
-DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960003 AS citus_table_alias (key, value) SELECT key, value FROM (SELECT test_table.key, test_table.value, test_table.other_value FROM cte_inline.test_table_1960003 test_table) fist_table_cte WHERE ((worker_hash(key) OPERATOR(pg_catalog.>=) 1073741824) AND (worker_hash(key) OPERATOR(pg_catalog.<=) 2147483647))
+DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_8531344307640482336 AS citus_table_alias (key, value) SELECT key, value FROM (SELECT test_table.key, test_table.value, test_table.other_value FROM cte_inline.test_table_1960003 test_table) fist_table_cte WHERE ((worker_hash(key) OPERATOR(pg_catalog.>=) 1073741824) AND (worker_hash(key) OPERATOR(pg_catalog.<=) 2147483647))
 DEBUG:  Plan is router executable

```

**Comment by onderkalaci** [comment] 2020-04-03 11:10
This is happening frequently: https://app.circleci.com/pipelines/github/citusdata/citus/7891/workflows/de43a8c5-b07c-4cbf-a4c1-f5763cbafd03/jobs/111664

**Comment by pykello** [comment] 2020-04-03 17:52
@serprex is working on this and I think he has figured out the root cause. This'll be fixed by end of release.

**Comment by serprex** [comment] 2020-04-03 20:39
Details outlined in #3688

**Comment by SaitTalhaNisanci** [comment] 2020-04-09 11:57
I started to see this failure very often. I think I saw it like 6 times in the last 10 runs.

**Closed** 2020-06-15 16:41 UTC
