### ISSUE TITLE
Distributed deadlocks may occur when writing to reference table

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1054] opened 2016-12-20 12:20 UTC
Reference tables (#1018) reveal some distributed deadlocks in the router executor which can occur when mixing replication models / factors. Shard resource locks now only apply to reference tables allowing distributed deadlocks between row-level locks on the worker and shard resource locks on the master (demonstrated below). This is a general problem with mixing replication models.

I think there's an additional problem which is that modifying a reference table allows you to subsequently modify shards in arbitrary order across workers as the placements are always on a subset of workers, which can also lead to distributed deadlocks. This seems like a bug in the transaction participation logic of the router executor.

In session 1:
```
SET citus.shard_replication_factor TO 1;

CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test', 'x');

CREATE TABLE ref (y int primary key, name text);
SELECT create_reference_table('ref');

INSERT INTO ref VALUES (3,4);
INSERT INTO test VALUES (3,4);

BEGIN;
UPDATE ref SET y = 3;
```

In session 2:
```
BEGIN;
UPDATE test SET y = 5 WHERE x = 3;
UPDATE ref SET y = 10;
[hangs on shard resource lock held by session 1 on master]
```

In session 1:
```
UPDATE test SET y = 10 WHERE x = 3;
[hangs on row-level lock held by session 2 on worker 1]
```

**Comment by ozgune** [comment] 2017-01-06 00:34
@marcocitus / @onderkalaci -- Are we planning on fixing this for our v6.1 release?

**Comment by onderkalaci** [comment] 2017-01-09 15:29
Hmm, with #1079 I cannot re-produce with the above steps. The main reason is that #1079 tries to get the connections before acquiring the executor locks. In that case, we get the following error in session 2:
```
ERROR:  no transaction participant matches localhost:9700
DETAIL:  Transactions which modify distributed tables may only target nodes affected by the modification command which began the transaction.
```

I'll look more whether it solves this problem in general or just fixes for this set of specific cases.

**Comment by onderkalaci** [comment] 2017-01-09 17:57
> I think there's an additional problem which is that modifying a reference table allows you to subsequently modify shards in arbitrary order across workers as the placements are always on a subset of workers, which can also lead to distributed deadlocks. This seems like a bug in the transaction participation logic of the router executor.

Giving an example to the above problem which is not solved by #1079:

Session 0:
```SQL



SET citus.shard_count = 4;
SET citus.shard_replication_factor = 1;


CREATE TABLE reference_table (a int);
SELECT create_reference_table('reference_table');



CREATE TABLE first_dist_table(a int, b int);
SELECT create_distributed_table('first_dist_table', 'a');

CREATE TABLE second_dist_table(a int, b int);
SELECT create_distributed_table('second_dist_table', 'a');


-- insert some data to trigger row-level locks
INSERT INTO first_dist_table VALUES (1, 1);
INSERT INTO first_dist_table VALUES (3, 3);


INSERT INTO second_dist_table VALUES (1, 1);
INSERT INTO second_dist_table VALUES (3, 3);
```

Session 1:
```SQL

BEGIN;
-- transaction partricipant list includes all nodes
INSERT INTO reference_table VALUES (1);

-- hits the first shard of first_dist_table
UPDATE first_dist_table SET b = 1 WHERE a = 1;

```

Session 2:
```SQL
BEGIN;
-- transaction partricipant list includes all nodes
INSERT INTO reference_table VALUES (1);

-- hits the second shard of second_dist_table
UPDATE second_dist_table SET b = 1 WHERE a = 3;
```


Session 1 again:
```SQL
-- hits the second shard of second_dist_table
UPDATE second_dist_table SET b = 1 WHERE a = 3;
```

Session 2 again:
```SQL
-- hits the first shard of first_dist_table
UPDATE first_dist_table SET b = 1 WHERE a = 1;
```

Now that both sessions are blocked.

**Comment by ozgune** [comment] 2017-01-12 23:10
@onderkalaci / @marcocitus / @anarazel -- I had a clarification question on this issue.

Marco originally reported two issues: (1) problems with mixing replication models / factors and (2) modifying a reference table subsequently allows you to modify shards in arbitrary order across worker nodes.

@onderkalaci has steps to reproduce the second issue that relates to reference tables. Are we thinking of fixing this for 6.2 or is the fix too complex?

@lfittl -- Do you foresee any scenarios in which we can run into this issue, or is it just not likely?

**Comment by lfittl** [comment] 2017-01-18 00:58
@ozgune The scenario that @onderkalaci describes could certainly happen - I've seen these kind of deadlocks on a single-node Postgres before, where they are caught by the deadlock detector. 

Unfortunately Rails in particular likes to encourage a pattern where users have long and complex transactions, that might deadlock against other similar transactions affecting the same rows.

That said, I don't think its a blocker per-se, but it is something we should warn users about, in my opinion.

**Comment by dangxunb** [comment] 2017-07-05 17:42
I faced this issue when batch insert 250 records via JDBC into a distributed table in a single-machine node (first-time test).

**Comment by anarazel** [comment] 2017-07-05 17:50
@marcocitus This should essentially be solved with the deadlock detection work (#1394 and sub-issues), right?

**Comment by dangxunb** [comment] 2017-07-05 18:02
In the meantime, what should I do to batch insert records?

**Comment by ozgune** [comment] 2017-08-17 23:01
@dangxunb -- If you share these steps in our [public Slack channel](https://citus-public.slack.com/messages/C0XRHT1KJ/), we'd be happy to help.

@onderkalaci -- Is this issue now resolved with the recently merged in deadlock detection changes? Also, is this issue a duplicate of #1328?

**Comment by onderkalaci** [comment] 2017-08-18 06:49
> - Is this issue now resolved with the recently merged in deadlock detection changes? 

Yes, that's right. I'm closing the issue.

> Also, is this issue a duplicate of #1328?

I think on that issue if the `SELECT`s are router selects, then the answer is yes. Also, looking into @lfittl 's internal email thread `Issue with reference tables in transactions`, the `SELECT`s are router.

I'm OK with closing that as well.

 (Note that we already do not support multi-shard selects in transactions, so I suspect the `SELECT`s are router.)

**Closed by onderkalaci** 2017-08-18 06:49 UTC
Labels: bug
