### ISSUE TITLE
Connection management: Convert existing callers

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#873] opened 2016-10-13 18:39 UTC
We're unifying our connection management logic in Citus as part of #704.

Once we come up with new APIs and the underlying implementation, we're going to start converting existing users to use the unified APIs. I'm opening this issue to track the conversion of existing callers to the new APIs.

We could also open separate issues for the items below, if it's easier to track them this way.
- [x] router executor
    - [x] get connections using the new API
    - [x] update function signatures to use `MultiConnection *` instead of `PGConn *` (see #1053 for the discussion)
    - [x] Move INSERT .. SELECT and DDL code in router executor over
- [ ] COPY (#1096)
- [ ] real-time executor
- [x] DDL + `master_modify_multiple_shards`
- [ ] Other user-defined functions (UDFs): 15 small UDFs (#1101)
- [x] 2PC recovery (#1099)
- [x] MX metadata sync

**Comment by anarazel** [comment] 2017-01-11 22:13
This essentially is a duplicate of the information in #704, which is confusing.

**Closed by anarazel** 2017-01-11 22:13 UTC
