### ISSUE TITLE
Distributed deadlock in MX mode when TRUNCATE tables on master node

### ISSUE THREAD

**Issue by exialin** [citusdata/citus#2625] opened 2019-03-12 06:21 UTC
Hi,

I encountered a distributed deadlock error when doing the following steps:
```sql
testdb=# create table t (c1 int, c2 int);
CREATE TABLE
testdb=# select * from create_distributed_table('t','c1');
 create_distributed_table 
--------------------------
 
(1 row)
testdb=# truncate t;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
```

Citus is in MX mode, and this error only happens on the **master node**.

Configuration:
PostgreSQL 11.1, Citus [master](https://github.com/citusdata/citus/tree/e813df4d7fc26262602b422a106f96143183a115) version with 2 nodes in MX mode

**Comment by onderkalaci** [comment] 2019-03-12 07:34
Hi @exialin thanks for this report. I cannot reproduce this using the steps mentioned above. In fact, we even have a very similar test in the regression [tests](https://github.com/citusdata/citus/blob/master/src/test/regress/expected/multi_mx_truncate_from_worker.out) which works fine.

So, would you mind sharing the previous steps (or in general more details on the issue) as well? Such as creating database, adding the nodes, setting the `citus.replication_model`, syncing the metadata , whether do you use pgbouncer or not, how many shards do you use, etc.

**Comment by exialin** [comment] 2019-03-12 09:42
@onderkalaci 
First, I initialized 2 Postgres instances and created Citus extension. Then I did the following steps on one node:
```sql
testdb=# select master_add_node('localhost', 9710);
                 master_add_node                  
--------------------------------------------------
 (1,1,localhost,9710,default,f,t,primary,default)
(1 row)

testdb=# select master_add_node('localhost', 9711);
                 master_add_node                  
--------------------------------------------------
 (2,2,localhost,9711,default,f,t,primary,default)
(1 row)

testdb=# set citus.replication_model to streaming ;
SET
testdb=# select start_metadata_sync_to_node('localhost', 9711);
 start_metadata_sync_to_node 
-----------------------------
 
(1 row)

testdb=# set citus.shard_count = 2;
SET
testdb=# create table t (c1 int, c2 int);
CREATE TABLE
testdb=# select * from create_distributed_table('t','c1');
 create_distributed_table 
--------------------------
 
(1 row)

testdb=# truncate t;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
```

I didn't use pgbouncer or any other extensions.

**Comment by onderkalaci** [comment] 2019-03-12 10:02
> First, I initialized 2 Postgres instances and created Citus extension. Then I did the following steps on one node:

Is the coordinator node running on `9710 ` or `9711 ?` You should do `master_add_node()` for worker nodes.

I guess you're adding the coordinator node as a worker node to the cluster as well, which is not [supported](https://github.com/citusdata/citus/issues/1792).

> testdb=# select start_metadata_sync_to_node('localhost', 9711);

Two more notes if you're trying to use two worker nodes. Citus MX is (currently) not intended to support only **some** nodes to have the metadata sync enabled. You should rather do `select start_metadata_sync_to_node(nodename, nodeport) FROM pg_dist_node;` to enable all. And, you should only do it on the coordinator.

**Comment by exialin** [comment] 2019-03-12 10:16
@onderkalaci 
I see. The coordinator node is running on `9710` and I run `master_add_node()` for both nodes. Actually I regard them both as worker nodes, so this is not correct?

If I indeed want to run with this configuration, I can do `truncate t` on worker node `9711`, right? Will this cause some side effects?

**Comment by onderkalaci** [comment] 2019-03-12 10:20
> Actually I regard them both as worker nodes, so this is not correct?

That's correct.

> If I indeed want to run with this configuration, I can do truncate t on worker node 9711, right? Will this cause some side effects?

You can either do it on 9710 or 9711.

The only side effect would be to acquire some locks on all other nodes to prevent any concurrency issues -- specific to `TRUNCATE`, which would be invisible to the user in most of the cases.

**Comment by exialin** [comment] 2019-03-12 11:47
@onderkalaci OK, thank you for the details!

**Comment by onderkalaci** [comment] 2019-03-12 11:53
I'm closing the issue, feel free to ask/discuss any further details on our [slack channel](https://slack.citusdata.com)

**Closed by onderkalaci** 2019-03-12 11:53 UTC
