### ISSUE TITLE
Unnecessary aggregation in coordinator

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#3305] opened 2019-12-14 01:54 UTC
It seems to me that when the group by key contains the distribution column we should be able to skip the extra aggregation in the coordinator, but we don't.

```sql
create table t1(a int, b int);
select create_distributed_table('t1', 'a');
explain select a, count(*) from t1 group by a;
                                       QUERY PLAN                                       
----------------------------------------------------------------------------------------
 HashAggregate  (cost=0.00..0.00 rows=0 width=0)
   Group Key: remote_scan.a
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=localhost port=5433 dbname=postgres
               ->  HashAggregate  (cost=43.90..45.90 rows=200 width=12)
                     Group Key: a
                     ->  Seq Scan on t1_102008 t1  (cost=0.00..32.60 rows=2260 width=4)
```

The coordinator `HashAggregate` seems unnecessary.

**Comment by marcocitus** [comment] 2019-12-14 06:56
Duplicate of #3292

**Closed by marcocitus** 2019-12-14 06:56 UTC
