### ISSUE TITLE
Transactions (which pass) with DMLs on reference tables are not cleared from pg_dist_transaction causing uniqueness violations

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#1619] opened 2017-08-23 21:18 UTC
**Citus version:** 6.2-4
**Table definition:**
```
CREATE TABLE ref(id int, tenant_id int);
SELECT create_reference_table('ref');
```
**Case1:**
```
citus=> SELECT * from pg_dist_transaction ;
 groupid | gid
---------+-----
(0 rows)

citus=> UPDATE ref SET id=1 where tenant_id=1;
UPDATE 1
citus=> SELECT * from pg_dist_transaction ;
 groupid |       gid
---------+-----------------
       2 | citus_0_26673_2
       1 | citus_0_26673_3
(2 rows)

citus=> UPDATE ref SET id=1 where tenant_id=1;
UPDATE 1
citus=> SELECT * from pg_dist_transaction ;
 groupid |       gid
---------+-----------------
       2 | citus_0_26673_2
       1 | citus_0_26673_3
       2 | citus_0_26673_4
       1 | citus_0_26673_5
(4 rows)

citus=> UPDATE ref SET id=1 where tenant_id=1;
UPDATE 1
citus=> SELECT * from pg_dist_transaction ;
 groupid |       gid
---------+-----------------
       2 | citus_0_26673_2
       1 | citus_0_26673_3
       2 | citus_0_26673_4
       1 | citus_0_26673_5
       2 | citus_0_26673_6
       1 | citus_0_26673_7
(6 rows)
```
**Case 2:**
```
citus=> SELECT * from pg_dist_transaction ;
 groupid | gid
---------+-----
(0 rows)
citus=> BEGIN;
BEGIN
citus=> UPDATE ref SET id=1 where tenant_id=1;
UPDATE 1
citus=> END;
COMMIT
citus=> SELECT * from pg_dist_transaction ;
 groupid |       gid
---------+-----------------
       2 | citus_0_26854_0
       1 | citus_0_26854_1
(2 rows)

citus=> BEGIN;
BEGIN
citus=> UPDATE ref SET id=1 where tenant_id=1;
UPDATE 1
citus=> END;
COMMIT
citus=> SELECT * from pg_dist_transaction ;
 groupid |       gid
---------+-----------------
       2 | citus_0_26854_0
       1 | citus_0_26854_1
       2 | citus_0_26854_2
       1 | citus_0_26854_3
(4 rows)
```
By continuous such DMLs(INSERTs, UPDATEs and DELETEs) which pass,
**pg_dist_transaction** gets heavily populated and at one stage there is an error(as below) which intermittently(every 8 inserts etc) seen:
**Unique constraint violation:**
```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_dist_transaction_unique_constraint"
DETAIL:  Key (groupid, gid)=(2, citus_0_24338_0) already exists.
```
The way to fix this is to constantly run **SELECT recover_prepared_transactions();**, say in a cron-job every minute. However this depends on the ingestion rate on the reference table.

**Out of memory issue:**
Running SELECT recover_prepared_transactions(); intermittently on the coordinator(4 cores and 15GB RAM) with heavy load (cpu >90%), one of the prospects ran into out of memory issue as below:
```
ERROR:  out of memory
DETAIL:  Failed on request of size 15.
```

**Comment by sumedhpathak** [comment] 2017-08-23 21:45
Based on conversation with @anarazel entries in `pg_dist_transaction` are expected even on successful 2PC transactions. 

The unique constraint violation issue is fixed in 7.0 as per @marcocitus .

Looks like the OOM might still be an issue, so that might need more investigation.

**Comment by ozgune** [comment] 2017-08-23 22:17
@saicitus -- #1574 would fix this issue. However, #1574 cleans up `pg_dist_transaction` by checking the transactions on each worker node. As a result, it may (or may not) introduce a performance overhead.

*If* #1574's performance becomes an issue, @anarazel suggested that we add another column to `pg_dist_transaction` that says whether the transaction committed or not. On commit, we flip that column to true. That way, #1574 could just remove old entries without checking with the worker.

**Comment by anarazel** [comment] 2017-08-23 22:27
> On commit, we flip that column to true.

Which is easier to do than deleting after commit, because `heap_inplace_update` exists.

I think we should then do the deletion of confirmed committed xacts requiring less heavyweight locks...

**Comment by marcocitus** [comment] 2017-08-24 08:53
> That way, #1574 could just remove old entries without checking with the worker.

Just to clarify: We still need to check with the worker since it may have prepared transactions that need to be aborted. The extra column would help when deleting takes a significant amount of time (e.g. when there are 100k 2PCs per minute), because we could avoid blocking other 2PCs while deleting those records.

**Comment by marcocitus** [comment] 2017-08-24 10:08
Note that the issue as described here is mostly fixed already by #1504.

**Comment by sumedhpathak** [comment] 2018-01-04 05:57
@marcocitus Can this issue be closed? We now auto-recover prepared transactions in 7.2.

**Comment by marcocitus** [comment] 2018-01-04 06:04
Yes

**Closed by marcocitus** 2018-01-04 06:04 UTC
