### ISSUE TITLE
Reference tables in multi-tenant use-case don't work on Cloud

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#760] opened 2016-08-30 18:29 UTC
In the multi-tenant use-case, the router planner expects and tries to find a scenario where all the shards involved in the query are located on a single node. For small reference tables this won't be the case in Citus Cloud. The router planner has no notion of 'broadcastable' tables, so it currently just errors out.

On cloud (without revisiting the replication factor) we have two options:
a. Ask users to denormalize the data to remove reference tables
b. Add tenant_id to reference tables as well (which makes updating these tables potentially cumbersome).

**Comment by onderkalaci** [comment] 2016-11-11 21:19
> On cloud (without revisiting the replication factor) we have two options:

It looks like we're going to re-visit the replication factor and set it to (#worker nodes) for reference tables. Then, we'll run a 2PC while modifying the reference tables. 

> The router planner has no notion of 'broadcastable' tables, so it currently just errors out.

Since shards would be replicated to all nodes, the queries will work. 

I'm noting here that we should add regressions test that specifically targets this use-case when we close the issue.

Also, given that `INSERT INTO ... SELECT` uses router planner, the test should include such queries as well.

**Comment by ozgune** [comment] 2017-01-03 23:40
@onderkalaci -- are you the right person to assign this to? 😃

**Comment by onderkalaci** [comment] 2017-01-05 06:54
> @onderkalaci -- are you the right person to assign this to? 

Sure, I'm the right person :) I'll be doing some sanity checks on Cloud this week.

**Comment by lfittl** [comment] 2017-01-05 08:26
@onderkalaci Happy to help test as well - are there any particular parts that might break, or are problematic with pgbouncer/etc?

**Comment by onderkalaci** [comment] 2017-01-05 12:34
> @onderkalaci Happy to help test as well - are there any particular parts that might break, or are problematic with pgbouncer/etc?

@lfittl I don't expect any integration problems. Also, I did some basic functionality testing on Cloud, all looks good so far.

But, if you have an easy test setup you could run on Cloud where there is a single shard table that could be converted into a reference table, please give it a try (and feel free to ping anytime you need need extra information).  

Almost all pieces are merged to the citus repo master branch (except for `master_remove_node()` and `mx-integration`, which are on the way).

I could then wait for some time to close this issue.

**Comment by lfittl** [comment] 2017-01-05 12:43
@onderkalaci Sounds good, I'll see if I can come up with a test case like that.

One more thing that came to mind, since I saw a recent PR on this - should we test adding nodes as well, making sure that the reference table gets copied to it?

**Comment by onderkalaci** [comment] 2017-01-05 12:56
> One more thing that came to mind, since I saw a recent PR on this - should we test adding nodes as well, making sure that the reference table gets copied to it?

> One more thing that came to mind, since I saw a recent PR on this - should we test adding nodes as well, making sure that the reference table gets copied to it?

Yes, I think adding such tests make sense.  We've just checked in `master_add_node()` PR. Once we check-in the remaining PRs, I'll send an e-mail explaining such new behaviors and features that come with reference tables.

**Comment by marcocitus** [comment] 2017-01-16 13:56
Can we close this issue?

**Comment by onderkalaci** [comment] 2017-01-17 08:23
> Can we close this issue?

Yes, I'm OK with closing this issue. I've already tested reference tables on Cloud with multi-tenant use case.

**Closed by onderkalaci** 2017-01-17 08:23 UTC
