### ISSUE TITLE
Debezium cannot auto create table when sink data from kafka

### ISSUE THREAD

**Issue by l1ttps** [citusdata/citus#7352] opened 2023-11-17 03:57 UTC
I faced issue with Redpanda, debezium and Postgresql. I tried connect with config "auto.create": "true" but it not working.

Debezium cannot auto create table if it is missing

I expect same doc:

> "auto.create": boolean
When enabled, automatically creates the destination table (if it is missing) based on the record schema (issues a CREATE). The default is disabled.

My Code: 
```js
 private async createConnectorSink(sinkConnection: SinkConnect, pluginId) {
        const { connect: { database, host, password, user, } } = sinkConnection
        const name = `${pluginId}`
        try {
            await this.connectorApi.delete(`connectors/${name}`)
        }
        catch (e) {

        }
        return this.connectorApi.post("/connectors",
            {
                name,
                "config": {
                    "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
                    "tasks.max": "1",
                    "connection.url": `jdbc:postgresql://${host}/${database}?useSSL=true`,
                    "connection.username": user,
                    "connection.password": password,
                    "insert.mode": "update",
                    "table.types": "TABLE",
                    "pk.mode": "record_value",
                    "topics": 'gateway.plugin.public.features',
                    "auto.create": "true",
                    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
                    "fields.whitelist": "id, value",
                    "auto.evolve": "true",
                    "table.name.format": "features",
                    "quote.identifiers": "true",
                }
            }
        )
    }
```

Both 2 cases if i fixed  "table.name.format": "features", or with default value table name format ("${topic}"). 

Error from connector on debezium:
``` 
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: JDBC sink connector failure
	at io.debezium.connector.jdbc.JdbcSinkConnectorTask.put(JdbcSinkConnectorTask.java:83)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	... 11 more
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to process a sink record
	at io.debezium.connector.jdbc.JdbcChangeEventSink.execute(JdbcChangeEventSink.java:87)
	at io.debezium.connector.jdbc.JdbcSinkConnectorTask.put(JdbcSinkConnectorTask.java:94)
	... 12 more
Caused by: java.sql.SQLException: Could not find table: features
	at io.debezium.connector.jdbc.JdbcChangeEventSink.alterTableIfNeeded(JdbcChangeEventSink.java:177)
	at io.debezium.connector.jdbc.JdbcChangeEventSink.checkAndApplyTableChangesIfNeeded(JdbcChangeEventSink.java:120)
	at io.debezium.connector.jdbc.JdbcChangeEventSink.execute(JdbcChangeEventSink.java:83)
	... 13 more
```

**Comment by thanodnl** [comment] 2023-11-24 14:30
> Redpanda, debezium and Postgresql
I fail to see how this is related to Citus.

The stacktrace you posted doesn't contain any hints that this is caused by a Citus error. Instead it seems that your problem is that the table `features` you have configured in your debezium config is missing. I am closing this for now.

If you believe this is a Citus issue, please explain why. Ideally you would either extract the error Citus gives to your application from the stacktrace, or find it in the logs. That is, if you are running against Citus. Which is not even clear from what you are writing.

**Closed by thanodnl** 2023-11-24 14:30 UTC
