### ISSUE TITLE
Concurrent create_distributed_table and drop table might deadlock if tables are colocated

### ISSUE THREAD

**Issue by velioglu** [citusdata/citus#1502] opened 2017-07-20 08:22 UTC
It is the reason behind the deadlock problem on the master branch. We have faced with it while running the parallel regression tests `multi_prepare_plsql.sql` and `multi_prepare_sql.sql`

In order to reproduce it, you need to create distributed table `colocated_table_1` while dropping another distributed table `colocated_table_2`, which is the only table colocated with `colocated_table_1`. The rease of the deadlock is : 
 
`CreateHashDistributedTable` takes(C-1) an `ExclusiveLock` on the `DistColocationRelationId()`, then `CreateColocatedShards` takes(C-2) an `AccessShareLock` on the ID of `colocated_table_2`, since it is the only table colocated with `colocated_table_1`.

`master_drop_all_shards` takes(D-1) an `AccessExlusiveLock` on the ID of `colocated_table_2` and `citus_drop_trigger` function takes(D-2) `RowExclusiveLock` on `DistColocationRelationId()` because it deletes the row from colocation table after checking there is no more table exist for this colocation group.

If these operations run in the order of C-1,D-1,C-2,D-2 then deadlock occurs.

In order to solve this issue, I have prepared a [PR](https://github.com/citusdata/citus/pull/1503) (thanks to Marco :)) which removes the delete operation within `citus_drop_trigger`. As a side effect, we may have dangling colocation groups on the colocation table now. PR also changes the type of lock on the `DistColocationRelationId()`to let concurrent `create_distributed_table` operations.

**Comment by onderkalaci** [comment] 2017-07-28 12:35
I think we may need a more comprehensive solution to this one. The similar issue (concurrent drop & create table) for reference tables leads to reference table with different colocation ids.

See below:
```SQL
 CREATE TABLE ref1(a int);
SELECT create_reference_table('ref1');
```
-- session 1
```SQL
BEGIN;
 CREATE TABLE ref2(a int);
SELECT create_reference_table('ref2');
```
-- session 2
```SQL
BEGIN;
DROP TABLE ref2;
```
-- session 1
```SQL
COMMIT;
```
-- session 2
```SQL
COMMIT;
```

-- any session
```SQL
 CREATE TABLE ref3(a int);
SELECT create_reference_table('ref3');

SELECT * FROM pg_dist_partition;
 logicalrelid | partmethod | partkey | colocationid | repmodel 
--------------+------------+---------+--------------+----------
 ref2         | n          |         |            8 | t
 ref3         | n          |         |            9 | t

SELECT * FROM pg_dist_colocation;
 colocationid | shardcount | replicationfactor | distributioncolumntype 
--------------+------------+-------------------+------------------------
            9 |          1 |                 3 |                      0

**Comment by marcocitus** [comment] 2017-11-20 13:42
We auto-closed this issue, but there was an additional, unrelated deadlock case that we did not address yet:
https://github.com/citusdata/citus/pull/1503#pullrequestreview-51132367

**Comment by onderkalaci** [comment] 2017-12-05 08:09
Since we've parallelized the regression tests more, we've started to observe this issue more and more. I regularly hit this issue on travis.

**Comment by metdos** [comment] 2017-12-05 08:19
Me too

**Comment by metdos** [comment] 2017-12-06 09:39
I can replicate this problem by running these scripts in parallel.

```bash

#!/bin/bash
for i in `seq 1 100000`;
do
    psql postgres -c "CREATE TABLE tableA_$i(id int);"
    psql postgres -c "SELECT create_distributed_table('tableA_$i', 'id');"
    psql postgres -c "DROP TABLE tableA_$i;"
done


#!/bin/bash
for i in `seq 1 100000`;
do
    psql postgres -c "CREATE TABLE tableB_$i(id int);"
    psql postgres -c "SELECT create_distributed_table('tableB_$i', 'id');"
    psql postgres -c "DROP TABLE tableB_$i;"
done
```

**Closed** 2017-12-06 11:03 UTC
Labels: bug
