### ISSUE TITLE
Stuck spinlock during MX pgbench

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2032] opened 2018-02-28 12:01 UTC
Ran into a PANIC during a pgbench run with tpcb-like workload on an 8-node Citus MX formation:
```
2018-02-28 11:58:28.862 UTC [32124][150/75022] : [3-1] [app=citus] PANIC:  stuck spinlock detected at GetBackendDataForProc, transaction/backend_data.c:587
2018-02-28 11:58:28.862 UTC [32124][150/75022] : [4-1] [app=citus] STATEMENT:  SELECT * FROM dump_local_wait_edges()
2018-02-28 11:58:28.945 UTC [16581][] : [15-1] LOG:  server process (PID 32124) was terminated by signal 6: Aborted
2018-02-28 11:58:28.945 UTC [16581][] : [16-1] DETAIL:  Failed process was running: SELECT * FROM dump_local_wait_edges()
2018-02-28 11:58:28.945 UTC [16581][] : [17-1] LOG:  terminating any other active server processes
```

**Comment by onderkalaci** [comment] 2018-02-28 12:22
Does the workload include distributed deadlocks? (May help to reduce the debugging efforts)

**Comment by marcocitus** [comment] 2018-03-12 10:12
> Does the workload include distributed deadlocks? (May help to reduce the debugging efforts)

I don't think so, just standard pgbench (tpcb-like)

**Comment by onderkalaci** [comment] 2018-07-26 13:06
We probably shouldn't have called `memcpy` while holding a spinlock

```C
	SpinLockAcquire(&backendData->mutex);

	memcpy(result, backendData, sizeof(BackendData));

	SpinLockRelease(&backendData->mutex);
```

See some related discussion in Postgres [hackers]( https://www.postgresql.org/message-id/flat/CAEepm%3D19x3CutECGF85xtHcTjyNSfg%3DDvCEgyc8mmnh4E-OJKA%40mail.gmail.com#d5a3b7c8e34b750bf7bbc7a57785e57f) list.

**Comment by onderkalaci** [comment] 2018-07-26 14:13
Hmm, maybe that's not the issue because `memcopy` seems like a safe function to call. 

Anyway, we should make sure that we're not doing any systems calls, throwing errors etc while holding `&backendData->mutex`.

**Comment by onderkalaci** [comment] 2018-08-17 08:13
I reproduced the issue on 1+12 c5.9xlarge cluster while running tpcb-like pgbench. I had seperate 3 driver nodes during the tests. pgbench options:  `-c 128 -j 64 -b tpcb-like`

```
2018-08-17 07:58:37.199 UTC [9035][52/936012] : [3-1] [app=citus] PANIC:  stuck spinlock detected at GetBackendDataForProc, transaction/backend_data.c:585
2018-08-17 07:58:37.199 UTC [9035][52/936012] : [4-1] [app=citus] STATEMENT:  SELECT * FROM dump_local_wait_edges()
2018-08-17 07:58:37.291 UTC [5298][] : [21-1] LOG:  server process (PID 9035) was terminated by signal 6: Aborted
2018-08-17 07:58:37.291 UTC [5298][] : [22-1] DETAIL:  Failed process was running: SELECT * FROM dump_local_wait_edges()
2018-08-17 07:58:37.291 UTC [5298][] : [23-1] LOG:  terminating any other active server processes
2018-08-17 07:58:37.291 UTC [9964][11/2005745] : [2-1] [app=[unknown]] WARNING:  terminating connection because of crash of another server process
```

**Comment by onderkalaci** [comment] 2018-09-14 13:49
## The issue in some more detail

- In the deadlock detection design, we concluded that prepared transactions cannot be part of a distributed deadlock. The idea is that (a) when the transaction is prepared it already acquires all the locks, so cannot be part of a deadlock (b) even if some other processes blocked on the prepared transaction,  prepared transactions would eventually be committed (or rollbacked) and the system will continue operating.
- With the above in mind, we probably had a mistake in terms of memory allocations. For each backend initialized, we keep a `BackendData` struct defined [here](https://github.com/citusdata/citus/blob/master/src/include/distributed/backend_data.h#L28)
- The mistake we made is that, we assumed there would only be `MaxBackend` number of backends, see [1](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/backend_data.c#L542), [2](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/backend_data.c#L566) and many other places in `backend_data.c`.
- However, `MaxBackends` doesn't include the prepared transactions and axuliary processes. When you check [`InitProcGlobal`](https://doxygen.postgresql.org/proc_8h.html#acd25c6e767b0c2f1834f5338f01e7a36)  you'd see that ` uint32      TotalProcs = MaxBackends + NUM_AUXILIARY_PROCS + max_prepared_xacts;`
- Also, the prepared transactions already shows up in the lock graphs. First, connect to a worker, and create a prepared transaction on a shard

```SQL
BEGIN;
TRUNCATE users_table_102008;
PREPARE TRANSACTION 'p1';
```
Later, connect to the coordinator and run a query on the same distributed table:
```SQL
BEGIN;
 SELECT count(*) from users_table;
```
Finally, get the wait edges and see that `blocking_pid` is `0`:
```SQL
SELECT * FROM dump_global_wait_edges();
-[ RECORD 1 ]----------------+------------------------------
waiting_pid                  | 97912
waiting_node_id              | 0
waiting_transaction_num      | 2
waiting_transaction_stamp    | 2018-09-14 13:53:44.274752+03
blocking_pid                 | 0
blocking_node_id             | 0
blocking_transaction_num     | 
blocking_transaction_stamp   | 
blocking_transaction_waiting | f
```



## What are the symptoms

- The issue description here where `GetBackendDataForProc ()` is a symptom in the sense that we're trying to acquire the spinlock `SpinLockAcquire(&backendData->mutex);` on an uninitialized memory, which is not 0 or 1. Thus, we never able to acquire the lock.
- In https://github.com/citusdata/citus-enterprise/issues/276, we see that, even if the task-tracker executor has not been used at all, we see some seg faults there. The common point between the task-tracker and the backend data is the shared memory.
- Given that the backend data is accessing out-of its scope, when it actually calls `SpinLockAcquire()`, it marks some memory location with `0x000000001`. And, if you look into the task-tracker's hash, which is on the shared memory, its value is ` (HASHELEMENT *) 0x100000000` see [here](https://github.com/citusdata/citus-enterprise/issues/276#issue-359058335). In fact `0x100000000` is actually a single bit of memory being set to 1 (e.g., `0000 0000 0001 0000 0000 0000 0000 0000 0000 0000 0000`). 
- Which is likely that the `SpinLockAcquire()` marks task-tracker's hash table's address with that value.

## How did we verify that we're accessing out-of the array we've initialized
- I initially added a log on [GetBackendDataForProc](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/backend_data.c#L749) where I added the following:
```SQL
	if (pgprocno > MaxBackends)
	{
		elog(LOG, "Process Id: %d Procno:%d, Orig Proc No: %d, "
				"MaxBackends: %d isBackgroundWorker: %d",proc->pid, pgprocno, origProcNo, MaxBackends, proc->isBackgroundWorker);

	}	
```
and it turned out to be there are lots of (really lots of) messages like the below:
```
2018-09-14 10:23:50.255 UTC [4368] LOG:  Process Id: 0 Procno:415, Orig Proc No: 415, MaxBackends: 312
2018-09-14 10:23:50.255 UTC [4368] STATEMENT:  SELECT * FROM dump_local_wait_edges()
```

Which clearly indicates that there are some prepared transactions (e.g., see `Process Id = 0`) and we're actually accessing out-of-the `backendManagementShmemData->backends` array (e.g., 415 > 312).

And, note that `max_prepared_transactions` is 100 and `NUM_AUXILIARY_PROCS`. Which actually indicates that the issue happens on the last Proc: `312` + `100` + `4` = `416`, where we observe the issue on the array's `415`th position, which is `416`th item in the array.

**Comment by marcocitus** [comment] 2018-09-14 14:10
Could including the processes have any side effects? e.g. would we see locks from auxiliary processes or mistakenly interpret a bunch of nodes with PID 0 as 1 node in the distributed deadlock detector?

**Comment by onderkalaci** [comment] 2018-09-14 15:31
As far as I can see, no it wouldn't have any side effects for prepared transactions. Note that we're already skipping prepared transactions when they are `waitingProc`s.  See `BuildLocalWaitGraph()` where we already skip `(currentProc->pid == 0)` at the beginning. However, we have no control over `blockingProc`. And, whenever we call `GetBackendDataForProc()` for `blockingProc` which is prepared tx, we'd access a non-allocated `backendData`.

Also, for other calls of `GetBackendDataForProc()` we have the same check where `(currentProc->pid == 0)` is skipped.

For example, there is not much (or any) value for using `TotalProcs` in `get_all_active_transactions()` or similar functions given that we're only considering distributed transactions (e.g., `transactionNumber != 0`). However, I didn't want to break the parity or deal with `NULL` pointers in the code for saving a small amount of memory.

I'm not very familiar with all of the `auxiliary`processes. But, still before the fix, any  `auxiliary`process as the `blockingProc` was problematic. For `waitingProc`, we're already covering `autovacuum` via `IsProcessWaitingForSafeOperations()` such that we ignore it.

We could potentially expand `autovacuum` check to something like `if (!AuxiliaryPidGetProc(proc->pid)) return false;` in `IsProcessWaitingForSafeOperations()`. What do you think?

**Comment by onderkalaci** [comment] 2018-09-14 15:53
And, one more note that any blocking prepared tx could never be a waiting process. That's why we seem to not need any modifications to the `while` loop in `BuildLocalWaitGraph()`. But, for readability/completeness, we might consider adding `if (waitingProc->pid == 0) continue`

**Comment by onderkalaci** [comment] 2018-09-17 06:56
> We could potentially expand autovacuum check to something like if (!AuxiliaryPidGetProc(proc->pid)) return false; in IsProcessWaitingForSafeOperations(). What do you think?

Reading through the Postgres code, I read the following comment on `InitAuxiliaryProcess()`:
```
 * Auxiliary processes are presently not expected to wait for real (lockmgr)
 * locks, so we need not set up the deadlock checker.  They are never added
 * to the ProcArray or the sinval messaging mechanism, either.  They also
 * don't get a VXID assigned, since this is only useful when we actually
 * hold lockmgr locks.
```

So, we should be safe by not considering them at all as we already do in the code?

**Closed** 2018-09-17 15:08 UTC
Labels: bug, mx
