### ISSUE TITLE
Out of shared memory error during JDBC testing

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#1617] opened 2017-08-23 17:23 UTC
I used JDBCReleaseTest.java file under our test-automation/jdbc.
Firstly I ran the tpch_create_hash_partitioned_tables.ddl which is in the same repo, under tpch_2_13_0 folder. After creating and distributing the table in a single machine Citus cluster (1C, 2W) I ran the JDBCReleaseTest.java just like test automation does;
```
javac JDBCReleaseTest.java
java -classpath postgresql-9.4.1212.jre6.jar:. JDBCReleaseTest
```
Of course you have to have a valid jdbc file. 
After starting the execution, just monitor the memory usage.
Even if the tables are empty, it's using massive amount of memory for a while and then it stops the execution with the following message 
![screen shot 2017-08-23 at 20 25 35](https://user-images.githubusercontent.com/6233557/29629388-46cfc724-8841-11e7-88c3-67dca96ba319.png)

If I run the query from the method which casued the error manually in psql, the error message becomes
![screen shot 2017-08-23 at 19 40 38](https://user-images.githubusercontent.com/6233557/29629184-943a4f4e-8840-11e7-8c06-827d95363b0c.png)

Execution ends in a point depending on your memory tho. In my local machine, it stoped at the test_no_4, but in a larger machine in EC2, it went up to simplePreparedTest1().

**Comment by furkansahin** [comment] 2017-08-24 12:54
Today, after trying in 2 more different machines in EC2 (c4.xlarge, m3.medium), I could not reproduce the problem.
However, it is continued to give the same error ```out of shared memory``` in my mac until I rebuild the whole cluster. In the new cluster, it works without a problem. The memory usage increases up to 1.5 GB but I assume this is because of replications we do internally. 
Yesterday, @mtuncer had a different error than mine for the same story and we tried it once more in his local. The error he gets is the following;
```
Exception in thread “main” org.postgresql.util.PSQLException: ERROR: out of memory
  Detail: Cannot enlarge string buffer containing 1073741811 bytes by 32 more bytes.
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
    at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
    at JDBCReleaseTest.executePreparedQueryWithTwoParam(JDBCReleaseTest.java:186)
    at JDBCReleaseTest.test_no_7(JDBCReleaseTest.java:100)
    at JDBCReleaseTest.main(JDBCReleaseTest.java:24)
```
This is pretty much the same issue. 
For anyone who wants to give it a try, the files I used to reproduce the problem are given in these links;
* https://gist.github.com/furkansahin/a0bcab833a19be1bad268245d51ddc55
* https://gist.github.com/furkansahin/dc24e1ea25c5709e85c2ae51a91f92aa

Ps. I realized that the problem was different in the first ss of this issue. I resolved it by adding 
``` SET citus.task_executor_type TO 'task-tracker';```

**Comment by anarazel** [comment] 2017-08-24 18:52
Hi Furkan,

On 2017-08-24 12:54:41 +0000, Mehmet Furkan ŞAHİN wrote:
> Today, after trying in 2 more different machines in EC2 (c4.xlarge, m3.medium), I could not reproduce the problem.
> However, it is continued to give the same error ```out of shared memory``` in my mac until I rebuild the whole cluster. In the new cluster, it works without a problem. The memory usage increases up to 1.5 GB but I assume this is because of replications we do internally. 
> Yesterday, @mtuncer had a different error than mine for the same story and we tried it once more in his local. The error he gets is the following;
> ```
> Exception in thread “main” org.postgresql.util.PSQLException: ERROR: out of memory
>   Detail: Cannot enlarge string buffer containing 1073741811 bytes by 32 more bytes.
>     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
>     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
>     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
>     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
>     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
>     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
>     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
>     at JDBCReleaseTest.executePreparedQueryWithTwoParam(JDBCReleaseTest.java:186)
>     at JDBCReleaseTest.test_no_7(JDBCReleaseTest.java:100)
>     at JDBCReleaseTest.main(JDBCReleaseTest.java:24)
> ```
> This is pretty much the same issue. 
> For anyone who wants to give it a try, the files I used to reproduce the problem are given in these links;
> * https://gist.github.com/furkansahin/a0bcab833a19be1bad268245d51ddc55
> * https://gist.github.com/furkansahin/dc24e1ea25c5709e85c2ae51a91f92aa
> 
> Ps. I realized that the problem was different in the first ss of this issue. I resolved it by adding 
> ``` SET citus.task_executor_type TO 'task-tracker';```

Could it be that you're preparing statements without freeing them ever?
If postgres returns an "out of memory" error, it'll log a memory context
dump to the server log. Could you perhaps post that?

**Comment by mtuncer** [comment] 2017-08-25 11:24
I was able to reproduce it in my local machine
for some reason nodeToString() function gets into a deep recursion inside ```multi_planner.c::CheckNodeCopyAndSerialization()``` since there are many repartition tasks outNode function end up requiring a very large memory.

Problem can be reproduced even when a shard_count = 4

**Comment by mtuncer** [comment] 2017-08-25 11:36
Verified that the query causing this issue
```sql
SELECT supp_nation::text, cust_nation::text, l_year::int, sum(volume)::double precision AS revenue FROM ( SELECT supp_nation, cust_nation, extract(year FROM l_shipdate) AS l_year, l_extendedprice * (1 - l_discount) AS volume FROM supplier, lineitem, orders, customer, ( SELECT n1.n_nationkey AS supp_nation_key, n2.n_nationkey AS cust_nation_key, n1.n_name AS supp_nation, n2.n_name AS cust_nation FROM nation n1, nation n2 WHERE ( (n1.n_name = 'RUSSIA' AND n2.n_name = 'UNITED STATES') OR (n1.n_name = 'RUSSIA' AND n2.n_name = 'UNITED STATES') ) ) AS temp WHERE s_suppkey = l_suppkey AND o_orderkey = l_orderkey AND c_custkey = o_custkey AND s_nationkey = supp_nation_key AND c_nationkey = cust_nation_key AND l_shipdate between date '1995-01-01' AND date '1996-12-31' ) AS shipping GROUP BY supp_nation, cust_nation, l_year ORDER BY supp_nation, cust_nation, l_year;
```
Completes but it takes very long (58sec) on my local machine

**Comment by ozgune** [comment] 2017-09-13 16:53
@furkansahin -- We may have three separate issues in this thread. Let's break them down and focus on one of them.

1. @mtuncer commented on an issue related to `CheckNodeCopyAndSerialization()`. We were also able to reproduce this issue in #542. This issue should be fixed in Citus 7.0 - unless assertions are enabled. This is a memory issue, not a "shared memory" issue.

2. Task tracker works like the following. When you issue a query, the coordinator breaks that query into query fragments and sends them worker nodes. Those query fragments then take shared memory on worker nodes. Once the query completes, the coordinator sends a cleanup task to worker nodes. This cleans up all shared memory allocated by query fragments.

If you're running on a dev box, your machine may be overloaded by work. In that case, the cleanup task may never get assigned to worker nodes. In that case, the shared memory could keep growing.

3. JDBC related issues. I haven't run tests from JDBC in a while. Could you try running the same test suite on your developer box without JDBC and see if you can reproduce the problem? 

If you can, it means the issue is with (2). If not, this issue could be related to JDBC.

**Comment by metdos** [comment] 2017-10-03 14:54
> Build postgresql in non-debug, non-assert mode. This issue is related to a build that has assertions turned on.

Do we know which assert causes this problem?

**Comment by marcocitus** [comment] 2017-10-03 14:57
> Do we know which assert causes this problem?

I think the issue is not an assert, but the fact that `CheckNodeCopyAndSerialization` only does stuff when assert is enabled.

**Comment by metdos** [comment] 2017-10-03 15:05
> I think the issue is not an assert, but the fact that CheckNodeCopyAndSerialization only does stuff when assert is enabled.

Ohh, right. I was searching for that assert block. Side effects of jetlag :)

**Comment by jasonmp85** [comment] 2017-10-03 20:44
> I think the issue is not an assert, but the fact that CheckNodeCopyAndSerialization only does stuff when assert is enabled

Yeah, when I saw "we only see this with asserts on" and `nodeToString`, that function was exactly what came to mind.

**Closed** 2021-03-16 13:40 UTC
