### ISSUE TITLE
Travis random failure with Failure testing framework

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2270] opened 2018-07-10 10:28 UTC
We time to time hit to an issue in travis with the failure testing automation framework.
The out we see is the following;
```
============== dropping database "regression"         ==============
NOTICE:  database "regression" does not exist, skipping
DROP DATABASE
============== creating database "regression"         ==============
CREATE DATABASE
ALTER DATABASE
============== installing citus                       ==============
CREATE EXTENSION
============== running regression test queries        ==============
test failure_test_helpers     ... ok
test failure_setup            ... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

```

**Comment by lithp** [comment] 2018-07-11 20:11
Hmmmm, interesting. This sounds hard to debug.

This seems likely to have been caused by the fifo, you'll block forever when trying to open the fifo if the other side never opens it. So, some theories:
- `mitmproxy` failed to start for some reason (the port was already bound?) and we block forever when attempting to talk to it.
- `mitmproxy` has crashed for some reason. It accepted the command but crashed and never responded?
- Travis runs multiple tests in the same machine? Very weird things happen if you have two proxies and one test process, the proxies often end up spin-looping and talking to each other and blocking the test process.

Some things which would be useful:
- It'd be nice to know which processes are running when we finally give up. `lsof -p `pgrep mitmdump` would be useful.
- It's generally bad that we block forever when attempting to open a fifo. I wish there was a way of setting a timeout from inside sql, but to add a timeout we probably need to write a c-function or switch away from using fifos. (fifos are really nice because they give us free synchronization, by the time the proxy has responded we know for sure that it's configured, but if the cost is that we often "oversynchronize" and deadlock then maybe it's worth switching to something else.

**Comment by onderkalaci** [comment] 2018-07-13 08:53
This came up several times again :/

**Comment by mtuncer** [comment] 2018-07-13 10:12
we should really fix this soon. It is way beyond little annoyance now. I would say more annoying than appveyor.

**Comment by metdos** [comment] 2018-07-16 08:04
@velioglu noted that this also currently fails nightly-merge-build.

@sumedhpathak, @lithp, we may need to disable failure testing framework until we fix this bug.

**Comment by lithp** [comment] 2018-07-20 20:00
@metdos @mtuncer @velioglu @onderkalaci How often does this happen? I opened a branch which dumps debug info if the failure tests every take more than 60 seconds to run, then I ran that branch on Travis 43 times and it failed once... the Ubuntu keyservers were down. I wasn't able to reproduce this hang.

**Comment by jasonmp85** [comment] 2018-07-20 23:19
FWIW this is what my Mac was doing when I first started running failure tests

**Comment by lithp** [comment] 2018-07-23 21:30
I was unable to reproduce the failure when I reduced the test suite to "only run failure tests". If you're having troubles this often then an easy solution is to just run the failure tests before any other test.

**Comment by jasonmp85** [comment] 2018-07-23 21:32
I mean the problem is less locally and more in Travis, right?

**Comment by lithp** [comment] 2018-07-23 21:34
I mean, [I pushed a branch](https://github.com/citusdata/citus/pull/2300) which only ran the failure tests, including a wrapper which dumps more information if they were to hang, and I was unable to make them hang after spending an entire morning just restarting the tests.

So, for some reason Travis works if the failure tests run first.

**Comment by onderkalaci** [comment] 2018-09-03 07:41
> I have faced with it again several times while preparing release branches.

That's expected, right? We've only merged the fix to the master (#2300), so if we need it in the releases, we should backport it?

**Comment by onderkalaci** [comment] 2018-09-13 07:47
Hmm, I haven't seen that after the PR (#2300) merged. I'll keep eye on this. 

Whenever anyone hits this again, it'd be useful to see the build output for reference. Btw, I've briefly looked into the recently failed [builds](https://travis-ci.org/citusdata/citus/builds), and haven't seen that? Actually, `master` doesn't seem to fail recently, except for some pg11 build failures.

**Comment by jasonmp85** [comment] 2018-09-13 14:37
I've seen this twice in the last day: a build is killed after 10m of no output during the failure tests. Lots of failure tests pass, but it reaches one and hangs. I saw it on a 10 build and now I've seen it on a 9.6 build. There is no meaningful output.

**Comment by onderkalaci** [comment] 2018-09-14 13:31
I've seen this as well.

**Comment by onderkalaci** [comment] 2018-09-27 14:59
A question:

Do we run the `citus-enterprise` and `citus` repos' travis builds on the same machine? I hit the same issue on enterprise tests today. So, if we concurrently run 2 failure test suites, we're likely to hit this issue, right?

**Comment by jasonmp85** [comment] 2018-10-09 22:44
Uh, probably not? They're within VMs or containers, or whatnot anyhow.

**Comment by onderkalaci** [comment] 2018-10-26 11:53
Happened once more on `failure_create_distributed_table_non_empty `

**Comment by marcocitus** [comment] 2019-10-01 21:36
We no longer use Travis for tests

**Closed by marcocitus** 2019-10-01 21:36 UTC
Labels: regression tests
