### ISSUE TITLE
Comprehensive schema support

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#122] opened 2016-02-03 19:34 UTC
See related items: #73, #77, #78

**Comment by onderkalaci** [comment] 2016-06-03 12:52
Here is my plan of attack on the comprehensive schema support:

Logical Groups for issues:
* **GROUP 1:** Issues related to deparsing table names, function names and type names when search path is set. This covers a lot of different examples and includes couple of different fixes: 
  * #267,#502, #556, #557, #560, #565, #555
* **GROUP 2:** Issues related to router planner deparsing
  * #215, #568
* **GROUP 3:** Issues related to de-parsing queries where the original queryTree is re-analyzed
  * #73
* **GROUP 4:** Issues related to worker_fetch_regular_table()
  * #504, Rebalancer [33](https://github.com/citusdata/shard_rebalancer/issues/33)
* **GROUP 5:** Issues related to not using quote_qualified_identifier on table/schema names in an in appropriate manner 
  * #78, #550
* **GROUP 6:** Issues related to ALTER TABLE 
  * #132
* **GROUP 7:** Issues related to Authorization. Note that, we're not able to test schemas with authorization due to the following bug. Once we fix it, we need to do more extensive tests.
  * Enterprise [136](https://github.com/citusdata/citus-enterprise/issues/136)

**The goal of this project:** Make sure that Citus can provide all of its functionality on schemas other than "public" schema. Similarly, ensure that schemas work as expected with Authorization. In the end, we'd expect to run a regression test file similar to this where almost all of the Citus functionality is executed on/cross different schemas.


**Very important notes for development and testing:**
* Make sure that the command is actually executed on the worker on the correct schema. This [issue](https://github.com/citusdata/citus/issues/73) is a good example that the user think it works, but, actually does not.
* Make sure that the fix works expected with table names that includes an escape character. A good example is this [issue](https://github.com/citusdata/citus/issues/550).
* Make sure that the fix works expected when the search path is set to "public" and "non-public".
* Make sure to add regression tests that covers all the changes.

**How to develop:** This task touches almost all parts of Citus. Tough, I don't think we'll need big changes in terms of LOC, we need to be cautious about we support schemas on all cases. 

I'd like to suggest *test driven development* for this task. That is having a single [comprehensive_schema_support](https://github.com/citusdata/citus/tree/comprehensive_schema_support) branch, and adding a regression test to it in which all tests fails in the beginning. Then, once we fix the issues, we merge the changes to that branch and expect to see that corresponding tests pass. In the end, we have a branch that all the tests pass and we do a final review/testing on the overall change. I know that this is not a common development method in the team, but, seems a good fit for a change that consists of small changes and touches a good number of outputs. But, if you think that it's not a good way to go, it's completely OK for me to fix issues one-by-one and merge them master, that's also viable approach.

Also, one reasoning for this approach is that having incremental schema support on the master does not help much. If someone is to use schemas, without checking in all the issues above, he'd be in trouble for some cases that he cannot solve without changing the code.

**Time estimations:** Looking into the v5.2 planning document, I think you've estimated 3 weeks of time (is that right?). It is more or less the same what I've in mind. I'm only not clear about multi-user (i.e., Authorization) part of it. My initial observation made me think that it's not a big change as well.


Thanks,
Onder

**Comment by sumedhpathak** [comment] 2016-06-03 21:50
@metdos Could you also tag the newly created sub issues with the 5.2 release milestone?

**Comment by metdos** [comment] 2016-07-18 13:09
After all of the issues above are fixed, we also need to remove the notice message schema support and update regression tests accordingly.

**Comment by byucesoy** [comment] 2016-07-22 14:17
About #210, we already create schemas during shard creation at worker nodes and creating database is not in the scope of schema support. Therefore I am leaving it open.

**Comment by metdos** [comment] 2016-07-22 15:15
Hey @sumedhpathak, from directly schema related issues https://github.com/citusdata/citus/issues/122#issuecomment-223570657 we only have the rebalancer issue remained. In the shard rebalancer, Travis tests use the debian package of Citus, so, first we need to release 5.2 and then merge shard rebalancer fix because shard rebalancer fix depends on Citus changes. On the other hand, shard rebalancer schema fix (branch) is ready for in-house testing.

**Comment by ozgune** [comment] 2016-07-25 17:47
@metdos / @byucesoy -- I'm updating the original comment on 02/10 and I'll next add another comment to reconcile any open issues with @onderkalaci's comment.

The following issues from the original list have been **resolved**:

* Issue #73 relates to schema support in ``master_apply_delete_command()``
* Issue #504 relates to joins with tables in another schema. The issue is with ``worker_fetch_regular_table()`` not respecting schema names. I also closed issue #77 as a duplicate of #504. The issue includes related bugs including shard rebalancer integration, joins and subquery pushdowns.
* Issue #78 relates to schema support in ``master_append_table_to_shard()``
* Issue #502 relates to schema support in ``master_create_empty_shard()`` when ``search_path`` is implicitly set. The root cause of the issue is that the master does not send `worker_apply_shard_ddl_command()` with schema name added. The issue is related to #267 and comes up on quite a few places.
* Issue #267 relates to always schema prefixing table/index names during shard creation. The issue also covers some other errors including `COPY dist_table FROM ..`, `master_create_empty_shard()`, `master_create_worker_shards()`, `CREATE /DROP INDEX` and `master_copy_shard_placement()`.
* Issue #215 relates to ``master_create_distributed_table()`` and ``master_create_worker_shards()`` propagating schema names to worker shards.
* Issue #132 relates to #25. We currently hook into ``CREATE SCHEMA`` commands for our warning messages, but overlook ``ALTER TABLE SET SCHEMA`` commands.
* Issue #555 relates to `COUNT DISTINCT` approximation when search_path is set. 
* Issue #556 relates to creating UDFs on different schemas. Might have a very similar solution as #267.
* Issue #560 relates to creating composite types on different schemas. Might have a very similar solution as #267.  
* Issue #557 related to using cstore_fdw (or any other fdw) on different schemas.
* Issue #565 is related to `ALTER TABLE` command. The error looks like very similar to #267, so fixing it *may* solve this as well.
* Issue #568 relates to `master_modify_multiple_shards()`. Similar to #215, the `deparse_shard_query()` ignores target schema. 
* Issue [136](https://github.com/citusdata/citus-enterprise/issues/136) on the enterprise repo related to schema support with authorization.

**Comment by ozgune** [comment] 2016-08-09 23:10
@byucesoy showed an impressive demo of our current schema support. We have a few open issues that are worth updating, but we consider them outside of the v5.2's scope.

I'm removing the v5.2 milestone from this issue and we'll evaluate open issues in upcoming release cycles.

**Comment by marcocitus** [comment] 2019-07-11 13:53
Seems almost all issues were resolved, so closing the parent.

**Closed by marcocitus** 2019-07-11 13:53 UTC
Labels: 1-2 weeks, in progress
