### ISSUE TITLE
could not establish asynchronous connection

### ISSUE THREAD

**Issue by hackermd** [citusdata/citus#1325] opened 2017-04-14 17:16 UTC
My log files are full of the following message:

```
WARNING:  could not establish asynchronous connection after 4000 ms
```

Sometimes I also get an error message like the following in between warnings. In all cases I have observed so far, these errors involve spatial Postgis queries:

```
ERROR:  failed to execute job 4196269
DETAIL:  Failure due to failed task 222
STATEMENT:
SELECT s.geom_polygon FROM mapobjects m
JOIN mapobject_segmentations s ON s.mapobject_id = m.id
WHERE m.mapobject_type_id = 7 AND m.ref_id = 170672
```

Tables `mapobject_segmentations` and `mapobjects` are both distributed by hash `mapobject_id` (`shard_replication_factor` is set to 1).

I am using Citus version `6.0-18` and Postgis `2.3.0` on Ubuntu `10.04` with 1 master and 4 worker nodes.

Any idea what's going wrong here?

**Comment by HackerMD** [comment] 2017-04-14 17:52
I should mention that I am running many (180) queries in parallel on a cluster and that reducing the complexity of the queries (selecting only points instead of large polygons) leads to less frequent errors.

**Comment by jasonmp85** [comment] 2017-04-17 08:06
Are you submitting these queries directly through `psql`, or are you using some sort of adapter for a language, like JDBC, `psycopg`, etc.?

I ask because this looks very similar to #902, which went away after changing some `psycopg` settings.

**Comment by HackerMD** [comment] 2017-04-17 08:15
I am using `psycopg2` (2.7.1) with `autocommit` enabled on connections.

**Comment by HackerMD** [comment] 2017-04-28 14:30
Any idea?

**Comment by ozgune** [comment] 2017-04-28 16:18
@HackerMD -- When I see these warnings, the most typical reason is that the worker nodes are overloaded. If you reduce the number of concurrent queries on the cluster, do these warnings go away?

At a higher level, when you send a query to the coordinator node, it opens multiple connections to the workers and sends query fragments over those connections. If the coordinator node doesn't hear back from the worker node for 4s (default), it then times out on the connection and tries to connect to another worker node. When the worker nodes are overloaded, we usually see these timeouts.

If you reduce the load on the cluster, does this warning go away? If it does, I'll close this as an issue -- happy to chat more about it in the citus-users list or our slack channel.

**Comment by lithp** [comment] 2017-05-08 07:50
Tentatively closing, but feel free to re-open if ozgune's comment doesn't work for you

**Comment by HackerMD** [comment] 2017-05-08 13:38
@lithp, sorry for not having responded yet. We are still investigating this issue on our side.

Could you be more specific about what you mean by "overloading"? We are monitoring the database servers via Ganglia and the available metrics look fine.

**Comment by lithp** [comment] 2017-05-09 09:30
@HackerMD As Ozgun said, these warnings are emitted when the coordinator attempts to open a connection with a worker node and the connection doesn't open within 4 seconds. There are a couple things which could cause this:
- If you're using pgbouncer (or another connection pooler) between the coordinator and workers you might be exceeding the maximum number of connections and blocking until new connections are available, you can test this by increasing the connection limit and seeing if the errors continue
- it's unlikely, but possible, that some network hardware between your coordinator and workers is hitting the maximum number of connections it can support.
- you might be experiencing high latency due to an overloaded network

You mentioned that running simpler queries causes the number of errors to decrease, it might be because these queries run faster, causing there to be fewer connections at any one point in time. You can try to reproduce by running pg_sleep() inside pgbench with various numbers of concurrent clients and sleep times. Since this will stress only the network and not the worker nodes themselves it should give you an idea of whether the network is truly the issue.

**Comment by hackermd** [comment] 2017-06-15 19:15
@ozgune

> When I see these warnings, the most typical reason is that the worker nodes are overloaded. If you reduce the number of concurrent queries on the cluster, do these warnings go away?

Reducing the number of concurrent queries did solve the problem. I think the problem is that the `WHERE` clause of the `SELECT` query doesn't include the partition key and therefore does not limit the query to a specific shard. The coordinator consequently needs to run the query on each shard and opens one or more (?) connections on each worker. Since multiple connections issue the same query to the coordinator in parallel (one per batch job), this will result in a large number of open connections on the workers.

Is there a way to cache queries results on the coordinator? Each batch job issues the same query within a short period of time. Ideally, the coordinator would run this query only once across all shards and return the cached result for all other connections that issue the same query. [PgPool II](http://pgpool.net/mediawiki/index.php/pgpool-II_3.2) seems to support query caching (and would also provide connection pooling). In a [recent blog](https://www.citusdata.com/blog/2017/05/10/scaling-connections-in-postgres) on connection scaling you recommend PgBouncer. Do you have any experience with PgPool for query caching?

**Comment by lithp** [comment] 2017-06-20 08:59
@hackermd We've considered caching but don't yet have anything built into Citus which will transparently cache for you. If you want to stick with pure Citus and can tolerate a few application changes Citus supports using unlogged tables:

```
CREATE UNLOGGED TABLE query_10_results AS (SELECT ...)
SELECT * FROM query_10_results;
```

By doing this you can cache results on the coordinator node.

We're aware of PgPool but prefer to stay away from it because it's complicated and packed with features, compared to pgbouncer which does one thing well and has always worked for us. I don't think we have any reasons for avoiding it save an abundance of caution so feel free to give it a try, but for lack of experience we can't help you with it.

If unlogged tables will do the trick and you want to minimize application changes there's a cheekier answer, a team member suggested a UDF like `cache_query_result('SELECT * FROM distributed_table ... ');` which creates and evicts the tables behind the scenes.

**Comment by ozgune** [comment] 2017-07-11 21:12
@hackermd -- I'm reading your last reply and we're happy to see that the issue has been resolved for you. I'll therefore close this issue.

If you have any other questions for us on connection pooling, please feel free to contact us on the citus-users list or Slack.

**Closed by ozgune** 2017-07-11 21:12 UTC

**Comment by apryor6** [comment] 2018-06-02 22:44
I have been experiencing this issue as well:

> WARNING: could not establish asynchronous connection after 5000 ms

My cluster is being used for real-time analytics, so by design it is frequent that a single query will touch many or all partitions in a large table. The number of table partitions I am using is approximately equal to the number of CPU cores across all nodes. When running a single simple query such as a `SELECT count(*)`, I see no issues and the query takes less than 1s. However, if a few are launched concurrently, the terminal is flooded with the above error and queries take drastically longer or fail entirely. I have pgbouncer configured on both the coordinator and worker nodes and have verified that the number of file descriptors available to the process is >8k. 

Under particularly heavy load, I will also see errors like:

> WARNING:  connection error: some-ip:6432
> DETAIL:  server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.

Inside the logs, I see many statements such as `LOG:  duration: 0.302 ms  statement: SELECT * FROM dump_local_wait_edges()` -- I have no idea if this is relevant.

I have also tried manually monitoring CPU usage through `top` on one of the coordinator nodes during this process, and I see a number of `postgres` processes equal to the number of partitions on that worker consuming ~20% CPU. This certainly seems far from overloading the resources, and the results of a `count(*)` should not be overloading the network. 

Any suggestions would be greatly appreciated.

**Comment by onderkalaci** [comment] 2018-06-04 11:09
Hi @apryor6,

> . I have pgbouncer configured on both the coordinator and worker nodes and have verified that the number of file descriptors available to the process is >8k.

A quick question: When you run the following command, what do you see in the `nodeport` field? Is that pgbouncer's port or the Postgres' port?
```SQL
SELECT * FROM pg_dist_node;
```

It might be that `pg_dist_node`, where Citus looks for to connect to the worker nodes, still points to the Postgres server?

**Comment by onderkalaci** [comment] 2018-06-04 13:49
>  and I have verified that the pooler is working by monitoring the number of connections over time on the workers.

How many connections are you seeing? In general, this kind of interactive discussions is solved much faster in our [slack channel](https://slack.citusdata.com/). Would you mind moving the discussion there?
