### ISSUE TITLE
UPDATE/DELETE with subqueries across multiple shards

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1740] opened 2017-10-30 15:10 UTC
Currently, you can do UPDATE/DELETE with subqueries, UPDATE/DELETE across multiple shards, but not both.

**Comment by onderkalaci** [comment] 2018-01-11 14:07
Closing since its duplicate of #1947 (actually the other duplicated this one, but we preferred to close this :) )

**Closed by onderkalaci** 2018-01-11 14:07 UTC
