### ISSUE TITLE
Joins do not work with tables in a different schema. This is because worker_fetch_regular_table does not respect schema name specified in the query.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#77] opened 2016-02-02 23:49 UTC
Joins do not work with tables in a different schema. This is because worker_fetch_regular_table does not respect schema name specified in the query.

**Comment by ozgune** [comment] 2016-05-06 22:30
I'm closing this issue as a duplicate of #504.

**Closed by ozgune** 2016-05-06 22:30 UTC
Labels: duplicate
