### ISSUE TITLE
Throw error when running TRUNCATE on distributed tables

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#540] opened 2016-05-19 14:11 UTC
#86 isn't in the roadmap to be fixed soon, so instead at least warn the user it won't work. We currently allow the command to run without removing any data.

**Comment by craigkerstiens** [comment] 2016-09-16 16:56
Adding some context here, as we actually do even worse than that. It truncates on the master which can reset sequences, meanwhile it silently fails on workers. This means in cases for CI/test processes if there's unique constraints on distributed tables inserts will fail since the sequence has been reset.

**Comment by saicitus** [comment] 2016-09-16 17:23
Hey Craig,I tested the above scenario. The TRUNCATE fails silently(which is an issue), but couldn't reproduce the  sequences getting reset. Correct me if I am missing something.
```
CREATE TABLE test_accounts(id serial, company_id integer, value text);
ALTER TABLE test_accounts ADD CONSTRAINT constraintname UNIQUE (id,company_id);
select master_create_distributed_table('test_accounts','company_id','hash');
select master_create_worker_shards('test_accounts',128,1);
INSERT INTO test_accounts(company_id) VALUES(1);
INSERT INTO test_accounts(company_id) VALUES(2);
INSERT INTO test_accounts(company_id) VALUES(3);
select * from test_accounts;
 id | company_id | value
----+------------+-------
  1 |          1 |
  3 |          3 |
  2 |          2 |
(3 rows)
TRUNCATE TABLE test_accounts;
TRUNCATE TABLE
select * from test_accounts;
 id | company_id | value
----+------------+-------
  1 |          1 |
  3 |          3 |
  2 |          2 |
(3 rows)
INSERT INTO test_accounts(company_id) VALUES(1);
INSERT 0 1
select * from test_accounts;
 id | company_id | value
----+------------+-------
  1 |          1 |
  4 |          1 |
  3 |          3 |
  2 |          2 |
(4 rows)
```

**Comment by anarazel** [comment] 2016-09-16 17:38
You're missing the restart identity option to truncate.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ozgune** [comment] 2016-09-16 17:41
Quick update. We decided to fix this issue by properly implementing ``TRUNCATE`` for distributed tables (#86).

@mtuncer has a pull request open for ``TRUNCATE``'s implementation in #721 and @jasonmp85's reviewing those changes. Once #721 gets merged, we'll have support for ``TRUNCATE``.

**Comment by mtuncer** [comment] 2016-09-28 11:06
#721  is just merged. I think we can close this issue now.

**Closed** 2016-09-28 18:31 UTC
Labels: bug, planned
