### ISSUE TITLE
subquery issue

### ISSUE THREAD

**Issue by mavencode01** [citusdata/citus#772] opened 2016-09-06 20:08 UTC
Am trying to execute the query 

`SELECT (exists(select true from "User" where "email" = $1)`

but got exception 

    ERROR:  cannot perform distributed planning on this query
    DETAIL:  Subqueries other than in from-clause are currently unsupported

Is there anyway I could re-write the same subquery ?

Thanks,

**Comment by sumedhpathak** [comment] 2016-09-06 21:09
@mavencode01 For questions like these, our Slack channel: https://slack.citusdata.com/ or our mailing list: https://groups.google.com/forum/#!forum/citus-users are more appropriate. We try to use Github issues only to track actual bugs or problems. 

We're also looking to document our workarounds in our [Documentation](http://docs.citusdata.com/en/v5.2/) , and should have some of those out this week.

For this specific issue, while its not ideal, you could do something like: 
```SQL
CREATE TEMP TABLE mytable AS (SELECT true FROM "User" where "email" = $1);
SELECT exists(SELECT * FROM mytable);
```

This isn't ideal, since we create the temp table on the master node, and has the potential to write a lot of data on the master. However, if your query contains the partition-column in the where-clause (e.g: SELECT (exists(select true from "User" where "email" = $1 and partition_column = 'xx')), we can push this down entirely to the workers. This is suitable for multi-tenant use-cases. 

To assist you further, feel free to use the above community support channels. Closing this issue however, since its a product question, and not a bug.

Thanks!

**Closed by sumedhpathak** 2016-09-06 21:09 UTC
