### ISSUE TITLE
Safe, unrestricted names for distributed tables and their objects

### ISSUE THREAD

**Issue by robin900** [citusdata/citus#781] opened 2016-09-11 00:47 UTC
Distributed tables, and some of their related objects, require "shard extension" of their names when worker shard tables (and related objects) are created for them. Currently, there are insufficient safeguards against object names becoming too long (longer than NAMEDATALEN) once they are shard-extended, with the possibility of name collision when more than one shard is created on a worker node.

There are some checks related to `master_create_worker_shards` but not in `master_create_distributed_table`. When `master_create_distributed_table` is called, the function raises no error, issues no notice, and creates the table metadata entry as-is. Then when `master_create_worker_shards` is called, if the table shard-extended name is not less than `NAMEDATALEN - 1`, all shard creation attempts fail because "the table name is too long to extend". So you're stuck with a distributed table that you can't make shards for.

The pull request #749 actually implements some missing shard-extended naming, by applying shard-extension to index-backed constraints; this PR has to include similar checks on the original name length, but I fear that the checks assume low shard ID values.

The following objects need their names shard-extended when part of a distributed table:

- Table
- Index
- Index-backed constraints: UNIQUE, PRIMARY KEY, EXCLUDE

The following objects do NOT need their names shard-extended:

- Column
- Non-index-backed constraints: CHECK

(Am I missing any named object type above?)

I believe that it's possible to have a safe, idempotent, CPU-independent function that shard-extends an object name into a name that:

- is always less than NAMEDATALEN, 
- reliably avoids collisions with all other shard-extended names,
- does not restrict the length of object names to be something less than `NAMEDATALEN - 1`.

Below is the algorithm in Python:

```
from clhash import get_unsigned_hash

SHARD_NAME_SEPARATOR = '_'
NAMEDATALEN = 64 # or whatever is configured for PG

def cpu_independent_32bit_hash(value):
    uint64_hash = get_unsigned_hash(value)
    return uint64hash & 0xFFFFFFFF

def shardExtendName(name, shardId):
    first_try = "%s%s%d" % (name, SHARD_NAME_SEPARATOR, shardId)
    if len(first_try) < NAMEDATALEN:
        return first_try
    shard_id_str = str(shardId)
    int32hashstr = "%08x" % cpu_independent_32bit_hash(name)
    truncated_name_length = (
        NAMEDATALEN - len(shard_id_str) - len(SHARD_NAME_SEPARATOR)
        - len(int32hashstr) - len(SHARD_NAME_SEPARATOR)
    )
    truncated_name = name[0:truncated_name_length]
    return (
        truncated_name + SHARD_NAME_SEPARATOR + 
        int32hashstr + SHARD_NAME_SEPARATOR + 
        shard_id_str
    )
```

There are [several CPU-independent hash functions](https://github.com/markokr/pghashlib#string-hashing-algorithms) to choose from. I think "lookup3le" using the least significant 32 bits would work great, and its implementation is in the public domain without license.

I'm ~~pretty sure~~ *certain* that this new shard-extended-name algorithm is fully backwards compatible. In all the ways that Citus 5.2 creates shard-related objects, `AppendShardIdToName` is used, and `AppendShardIdToName` does a final check and throws a show-stopping error for any extended name whose length after adding the separator and shardId would be `>= NAMEDATALEN`. In the above algorithm, the first case succeeds for any (name, shardId) combination that would pass this final check, and produces the same extended name as Citus 5.2. (In fact, Citus 5.2 code mistakenly rejects any name whose length after adding separator and shardId is `>= NAMEDATALEN - 1`, but the above statement still holds.

**Comment by robin900** [comment] 2016-09-14 14:52
Ah, I understand the `extendedNameLength = strlen(extendedName) + 1` thing now, it's for the palloc. Actually I think the extendedNameLength itself can be `== NAMEDATALEN`, so the final check would be `> NAMEDATALEN` since extendedNameLength is counting the null byte.

**Comment by robin900** [comment] 2016-09-14 14:56
I have a [working feature branch here.](https://github.com/robin900/citus/tree/new-extend-names) It incorporates lookup3_littlehash, and tests (which don't test the name extension logic yet) pass. I still need to address `AppendShardIdToStringInfo`, and write sufficient tests for the suite.

**Comment by robin900** [comment] 2016-09-14 17:22
Tests now cover the name extension logic.

**Comment by ozgune** [comment] 2016-09-15 17:32
@robin900 -- thanks for the detailed issue description. Do you think #179 is a duplicate of this issue?

**Comment by robin900** [comment] 2016-09-15 20:28
Yes it seems to be a duplicate.

**Closed** 2016-10-03 21:17 UTC
