### ISSUE TITLE
Automated valgrind test runs

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1039] opened 2016-12-12 23:20 UTC
Besides the work done in #835 we also need to make the run free from spurious failures:
- due to timeouts some tests still fail, we need to make
  REMOTE_NODE_CONNECT_TIMEOUT configurable ( #912)
- due to slow queries, autovacuum analyzes some tables, causing
  different plans. This probably should be fixed by adding explicit
  analyze statements to those
- should we verify that postgres was compiled with USE_VALGRIND
  specified? Probably not worth the effort.

**Comment by aamederen** [comment] 2016-12-13 08:09
For context, I have done some work on this within 6.0 release cycle.

**Comment by aamederen** [comment] 2017-03-23 08:05
So, I have tried to clear what has been done for valgrind tests to be run up in [valgrind-support branch](https://github.com/citusdata/citus/tree/valgrind-support). It increases some timeout values since tests are much much slower than regular regression tests.

# Steps to run valgrind tests
1. Checkout `valgrind-support` branch.
2. Configure postgres with `-DUSE_VALGRIND` option, this is the command that I use for configuration: `./configure --enable-cassert --enable-debug --with-openssl CFLAGS="-ggdb -g3 -O0 -fno-omit-frame-pointer -DUSE_VALGRIND"`. Of course you need to recompile postgres and citus after configuring with `-DUSE_VALGRIND`
3. Run valgrind regression tests with `make check-multi-vg`

# Remaining Items
1. Explain output in regression tests differ from regular tests. I have put `VACUUM ANALYZE` commands after data loading scripts but it didn't help. I think proper `VACUUM`ing the tables (with `FULL` and `ANALYZE`) should help. [This](https://gist.github.com/aamederen/4738631bb5e568e5526d399839ab0bef) is the regression.diffs output from the latest test.
2. We see random regression test differences due to missing `ORDER BY`s on some queries. It would help to put ORDER BY's to such queries in the context of this task.
3. Testing `multi-test-vg` itself for checking whether it actually catches memory leaks by injecting memory leaks by hand.

# Notes
- You may not want use the machine that is running `multi-check-vg` for other daily activities. For that, we were using a Google Compute Engine instances. I was using the machine called "citus-valgrind" for running tests manually and it appears that @anarazel has a machine "andres-postgres-valgrind-buildfarm-v2" which may hold valuable scripts in it, I don't know 😏 .
- There was a discussion about running valgrind tests nightly. I think travis is not an option since it is not suitable for long running (5-10 hours) tests. Unless there is a quick and easy option, I personally believe that it may not worth the effort to create manual scripts for automating nightly checks and sending reports in case something fails etc. In our test-automation project, we have infrastructure for running valgrind tests. We can use this to manually run the tests (during release testing phase), check the results and destroy the cluster.
- As of today, valgrind still doesn't work on macos sierra.

**Comment by metdos** [comment] 2017-04-21 13:56
Shall we keep this issue open until we merge https://github.com/citusdata/valgrind-test-automation/pull/1?

**Comment by byucesoy** [comment] 2017-07-18 08:00
Closing this since valgrind test automation is live in our KPI machine.

**Closed by byucesoy** 2017-07-18 08:00 UTC

**Comment by sumedhpathak** [comment] 2017-07-18 17:47
Thanks Burak! 🍾
