### ISSUE TITLE
Repartition Joins May Fail From Workers If JobId Sequences Overlap

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1147] opened 2017-01-20 09:15 UTC
In MX, when the jobids are the same of repartition joins on different workers, the task tracker may fail. It is a bit difficult to reproduce this error but repeated runs of [this gist setup](https://gist.github.com/aamederen/2e17bf34e1d37a5ca70169337af0e46d) helps producing it.

The cause seems like jobs and task that have the same jobid/taskid but belong to different queries collide with each other. A solution could be ensuring that jobid sequences are set to unique ranges on workers (as in BIGSERIAL columns of MX tables).

The error messages that arise include but not limiting to the following:
```
WARNING:  could not open file "base/pgsql_job_cache/job_10001/task_000030": No such file or directory
```

```
WARNING:  could not send remote query "SELECT task_tracker_task_status(10001, 33)"
DETAIL:  Client error: another command is already in progress
```

```
WARNING:  could not send remote query "SELECT task_tracker_assign_task  (10001, 2147483647, 'SELECT task_tracker_cleanup_job(10001)')"
DETAIL:  Client error: another command is already in progress
```

```
WARNING:  could not assign cleanup query for job 10001 to node "localhost:3701"
ERROR:  failed to execute job 10001
```

```
WARNING:  could not find the worker task
DETAIL:  Task jobId: 10000 and taskId: 30
```

**Comment by marcocitus** [comment] 2017-01-20 09:38
Seems like a duplicate of #1132

**Closed** 2017-01-22 16:06 UTC
Labels: bug, mx, needs review
