### ISSUE TITLE
Unexpected node type error in forced function call delegation

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#5673] opened 2022-02-01 13:46 UTC
The following gives a strange error message:

```sql
CREATE OR REPLACE FUNCTION test(x int)
RETURNS int
AS $$
DECLARE
BEGIN
    RETURN x;
END;
$$ LANGUAGE plpgsql;

SELECT create_distributed_function('test(int)','x',force_delegation:=true);

DO $$
BEGIN
    PERFORM test(3);
END;
$$ LANGUAGE plpgsql;
ERROR:  unexpected plan node type: 35
CONTEXT:  PL/pgSQL function inline_code_block line 3 at PERFORM
```

**Comment by tejeswarm** [comment] 2022-02-02 19:39
@marcocitus  I couldn't reproduce this on community, are there steps involved in repro? 
```
DROP TABLE IF EXISTS test_perform;
CREATE TABLE test_perform(i int);

SELECT create_distributed_table('test_perform', 'i', colocate_with := 'none');

CREATE OR REPLACE FUNCTION test(x int)
RETURNS int
AS $$
DECLARE
BEGIN
    RAISE NOTICE 'INPUT %', x;
    RETURN x;
END;
$$ LANGUAGE plpgsql;

SELECT create_distributed_function('test(int)', 'x',
                colocate_with := 'test_perform', force_delegation := true);
DO $$
BEGIN
    PERFORM test(3);
END;
$$ LANGUAGE plpgsql;

```

**Comment by tejeswarm** [comment] 2022-02-05 23:38
Fixed in PR https://github.com/citusdata/citus/pull/5686

**Closed by tejeswarm** 2022-02-05 23:38 UTC
Labels: bug, dev_reported
