### ISSUE TITLE
Add support for DISTINCT queries.

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#625] opened 2016-06-27 15:44 UTC
Currently we throw this error:

```
select distinct(column_name) from table_name;
ERROR:  cannot perform distributed planning on this query
DETAIL:  Distinct clause is currently unsupported
```

Even though this query is supported and returns the same thing:

`SELECT column_name FROM table_name GROUP BY column_name`

**Comment by ozgune** [comment] 2016-10-07 18:20
@lithp -- I'm noting this issue as a duplicate of #144.

If you think the two issues are unrelated, could you reopen #144?

**Comment by lukashes** [comment] 2016-10-17 14:28
Any news about `disinct(column)`? 

Simple query `SELECT distinct(campaign) FROM stats WHERE action_date = "2015-01-01"` is impossible.  

I used temporary tables, but it is annoying: 
> CREATE TEMPORARY TABLE distinct_campaigns AS SELECT campaign FROM stats WHERE action_date = "2015-01-01" GROUP BY 1

**Comment by lithp** [comment] 2016-10-17 15:08
@lukashes Why do you need the temporary table? You can just run the query you provided? `SELECT campaign FROM stats  WHERE action_date = "2015-01-01" GROUP BY campaign;`

**Comment by lukashes** [comment] 2016-10-17 15:54
@lithp Because I need set of data for doing other things. For example:

> SELECT count(*) FROM staff WHERE campaing IN (SELECT distinct(campaign) FROM stats WHERE ...)

Also. It useful for doing `count(distinct(column))` if I know that size of unique values of `column` is really small.

**Comment by lithp** [comment] 2016-10-17 16:01
@lukashes I guess I don't know SQL well enough, in my mental model the GROUP BY is equivalent to the DISTINCT. Why can't you do: `SELECT count(*) FROM staff WHERE campaign IN (SELECT campaign FROM stats WHERE [...] GROUP BY campaign)`? What about the number of unique values makes one more suitable than the other?

**Comment by lukashes** [comment] 2016-10-17 16:21
@lithp citus can't do this: 

> postgres=# select * from (select campaign from stats where action_day >= now()::date group by 1) as t;
ERROR:  cannot perform distributed planning on this query
DETAIL:  Subqueries without aggregates are not supported yet

**Comment by lithp** [comment] 2016-10-18 10:58
@lukashes yes, good point :) I'm not aware of anything on the roadmap which makes this easier but let me ask around for you.

**Comment by lithp** [comment] 2016-10-24 11:48
@lukashes 

Sorry for taking a while to get back to you! Looking at this again, I think your first query: `SELECT count(*) FROM staff WHERE campaign IN (SELECT distinct(campaign) FROM stats WHERE ...)`

can be written `SELECT count(*) FROM staff INNER JOIN stats USING(campaign) WHERE ...`

But if you have more complicated queries which actually require subqueries we have a flag you can toggle: `SET citus.subquery_pushdown TO 'true';`. It's not quite ready for prime-time, there are some conditions for using it which it doesn't enforce (and if you don't meet those conditions it might return incorrect results). Send an email to engage@citusdata.com with your query and more information on your schema and we'll help you know whether that flag is the right fit.

**Comment by samay-sharma** [comment] 2017-06-01 23:36
+1; requested from 2 customers.

**Closed** 2017-10-13 11:59 UTC
Labels: feature
