### ISSUE TITLE
Cannot upgrade to PostgreSQL 9.6 while Citus extension is installed

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#943] opened 2016-11-03 09:19 UTC
When trying to run pg_upgrade to upgrade a database with the Citus extension created from PostgreSQL 9.5 to PostgreSQL 9.6, we get the following errors during pg_upgrade:

```
Restoring database schemas in the new cluster
  postgres                                                  
*failure*

Consult the last few lines of "pg_upgrade_dump_13294.log" for
the probable cause of the failure.
Failure, exiting
```

in pg_upgrade_dump_13294.log:

```
pg_restore: creating TYPE "citus.distribution_type"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 624; 1247 16868 TYPE distribution_type marco
pg_restore: [archiver (db)] could not execute query: ERROR:  cache lookup failed for pg_dist_partition, called to early?
```

This particular error is triggered by a call to DistPartitionRelationId in CitusHasBeenLoaded(), which gets called via ProcessUtility during the upgrade process. If we prevent that call from erroring out by changing it to:

```
distPartitionRelationId = get_relname_relid("pg_dist_partition", PG_CATALOG_NAMESPACE);
```
then we run into the next error:
```
pg_restore: creating TABLE "pg_catalog.pg_dist_colocation"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 196; 1259 17042 TABLE pg_dist_colocation marco
pg_restore: [archiver (db)] could not execute query: ERROR:  permission denied to create "pg_catalog.pg_dist_colocation"
DETAIL:  System catalog modifications are currently disallowed.
    Command was: 
```
Note that this is not specific to pg_dist_colocation, it just creates tables alphabetically.

We don't really have a way to work around this error, so we probably have to drop the extension before pg_upgrade and recreate it after.

**Comment by anarazel** [comment] 2016-11-03 09:39
Nasty hack suggestion: If BinaryUpgradeMode is on, fudge allow_system_mods to on in our code.

**Comment by mtuncer** [comment] 2016-11-03 10:12
@anarazel I did not follow what you mean by allow_system_mods

**Comment by marcocitus** [comment] 2016-11-03 10:35
I think Andres means doing something like this in the ProcessUtility hook:

```
if (IsBinaryUpgrade)
{
    SetConfigOption("allow_system_table_mods", "true", PGC_POSTMASTER, PGC_S_OVERRIDE);
} 
```

I just tried this and it does actually work after also adding an IsBinaryUpgrade check to CitusHasBeenLoaded.

**Comment by mtuncer** [comment] 2016-11-03 11:47
Verified that pg_upgrade completed upon making above change and putting appropriate check to ```CitusHasBeenLoaded()```

However, pg_upgrade DOES NOT copy our metadata in pg_catalog namespace. pg_catalog.pg_dist_partition, pg_catalog.pg_dist_shard ..., all comes empty.  Also, sequences are at their default values.

This may led a user to believe their database is successfully upgraded, but cause them to loose their metadata. 

Here is the [document](https://docs.google.com/document/d/1Bq7taiISqhaSRiuNpM6qb2JPsI2DMpEowcIVHKt2pz8/edit#) outlining upgrade steps. We drop citus extension to perform the upgrade, and restore the metadata afterwards.

**Comment by jasonmp85** [comment] 2016-11-04 18:25
Unrelatedly, _called to early?_ is a typo and looks bad.

**Comment by jasonmp85** [comment] 2016-11-04 18:33
I'm not horribly familiar with `pg_upgrade `, but can't we tell which "side" of the upgrade we're on by checking the `PGVERSION` in our code?

Maybe we can copy metadata rows to a user table during the `9.5` phase, then copy them back into the catalog tables during the `9.6` phase (I guess in the extension load hook?)

Just spitballing.

**Comment by marcocitus** [comment] 2016-11-05 05:53
Not really, 9.5 code is not executed at pg_upgrade time afaik.

**Comment by mtuncer** [comment] 2016-11-08 18:23
there is a [discussion](https://github.com/citusdata/citus/issues/200) on CitusHasBeenLoaded()

**Comment by mtuncer** [comment] 2016-11-08 21:36
Me, Ozgun, Marco, and Sumedh had a discussion on the issue and alternate approaches.

## pg_upgrade failures and fixes

There are few issues that prevented pg_upgrade from working.

### 1 - A utility call during restore step calls CitusHasBeenLoaded which fails with the following error.
```
pg_restore: [archiver (db)] could not execute query: ERROR:  cache lookup failed for pg_dist_partition, called to early?
```
This is caused by our fix to a different bug (drop extension) which decides load state by also checking existence of pg_dist_partition. 

There is a possible fix to for this by making this check when we are not upgrading by checking  IsBinaryUpgrade flag.

### 2 - pg_catalog tables are not created during upgrade. Error message is 
```
pg_restore: [archiver (db)] could not execute query: ERROR:  permission denied to create "pg_catalog.pg_dist_colocation"
DETAIL:  System catalog modifications are currently disallowed.
```
@anarazel  mentioned a hack to be called in pg_init when we are in upgrade mod.

```
SetConfigOption("allow_system_table_mods", "true", PGC_POSTMASTER, PGC_S_OVERRIDE);
```
We do not know how safe is this hack yet. Need to do more investigation.


### 3 - Table contents created by extensions are not dumped by default.

There is a way to dump extension table contents as outlined here. A function pg_catalog.pg_extension_config_dump() let's table and sequence contents (not definitions) to be dumped. We could use this in a pre-upgrade script to add it to the dump list. Even better, we can do this during meta data/sequence creation time too. Needs to be verified and tested.

### 4 - OIDs might be incorrect for meta data tables/user tables/custom types.
We haven't really run an extensive tests on that. pg_dist_partition,  and pg_dist_colocation tables rely on type OIDs for partition columns.  Need to verify that this is not an issue or find a soluion.

### 5 - Sequences are not set after pg_upgrade

```pg_dist_shard_id_seq, pg_dist_groupid_seq, pg_dist_node_nodeid_seq,``` and ```pg_dist_colocationid_seq``` are not set. We manually reset them using meta data information on the related tables.

Solution to meta data table contents should also fix this. Needs verification.

### Evaluation

Fixing these problems require some investigation, a code change and testing on Citus side.  We have left this to post 6.0. 

There is an alternate method to make pg_upgrade succeed without a code change.

## Alternate Method
We have a working albeit somewhat ugly upgrade steps that let's pg_upgrade succeed. We prevented Citus from getting in the way of pg_upgrade by dropping the extension before upgrade, and re-create it afterwards. We had to address following issues.

1. Citus extension should be upgrade to 6.0 in the source instance before pg_upgrade. This also requires source instance must be using postgresql 9.5 because Citus 6.0 won't compile on pre-9.5 versions.
2. Citus extension is needed to be dropped in source instance and re-created on the target intance after upgrade. A destructive operation.
3. Truncate triggers on distributed tables are lost, needed to be re-created. Otherwise truncate function would not work.
4. OIDs in pg_dist_partition and pg_dist_colocation seem to be fine, but haven't run extensive tests on that. Needs verification.
5. Metadata sequences needed to be reset.
6. Dependency links between distributed tables and Citus extension needed to be broken on source instance, and re-created on target instance. 
7. Metadata tables dumped/restored manually

We were more inclined to solve problems with pg_upgrade and provide better user experience.

## Action Items

1. Fix CitusHasBeenLoaded() function to not to fail during upgrade.
2. investigate  allow_system_table_mods setting and make sure it is used in a safe matter.
3. ensure OIDs used in metadata tables are still valid after upgrade
4. ensure metadata table contents and sequence contents are copied to target instance correctly.
5. Prepare new upgrade steps afterwards.

**Comment by mtuncer** [comment] 2016-11-08 21:41
@anarazel responded

About upgrade workaround

> I just want to make sure that we're on the same page here: As far as I
> know pg_upgrade with the extension loaded has never done something
> meaningful.  So this isn't really a 6.0 regression - the symptoms
> changed a bit, that's it.  I think adding proper pg_upgrade / pg_dump
> support is a feature, and should be treated & scheduled as such. We
> haven't done that so far for 6.1.

About ```SetConfigOption("allow_system_table_mods", "true", PGC_POSTMASTER, PGC_S_OVERRIDE);```
> Should be safe.

About correctness of OIDs in metadata tables after upgrade

> It should be fine after the regclass fix for the table oids themselves,
> but partitioning column types / operators for pg_dist_partition might be
> problematic. We probably should change the type of the column. Hm

.

**Comment by mtuncer** [comment] 2016-11-12 01:20
also opened #980 to track non-addressed parts

**Comment by mtuncer** [comment] 2016-11-12 01:37
removed high priority label since changes with partial fix is merged.

**Comment by sumedhpathak** [comment] 2016-11-28 18:32
@mtuncer / @marcocitus can we close this issue? @mtuncer Does #980 capture all remaining open items?

**Closed** 2016-11-28 21:53 UTC
Labels: bug
