### ISSUE TITLE
Connection leak

### ISSUE THREAD

**Issue by mjaszczyk** [citusdata/citus#902] opened 2016-10-24 11:16 UTC
Hi,
I'm evaluating Citus on a test cluster on which I observe master-workers connection pool leak issue. The cluster is 1 x master and 3 x workers, all nodes are connected in the local network. The OS is Debian 8 and Citus 5.2.

The issue can be easily reproduced even using `psql`:
- Enable connect/disconnect logging on master and workers
- Connect to the master using `psql`. There should be connection logged on the master and nothing yet on the workers. 

```
2016-10-24 09:54:28 UTC [21210-1] [unknown]@[unknown] LOG:  connection received: host=[local]
2016-10-24 09:54:28 UTC [21210-2] postgres@test LOG:  connection authorized: user=postgres database=test
```
- Execute a query against distributed table. On the workers there is plenty of connect/disconnect logs. Basically these three logs for each query and shard. It looks like connection lasts only for single shard query.

```
2016-10-24 10:02:50 UTC [9536-1] [unknown]@[unknown] LOG:  connection received: host=xxx.xxx.xxx.xxx port=47694
2016-10-24 10:02:50 UTC [9540-2] postgres@test LOG:  connection authorized: user=postgres database=test
2016-10-24 10:02:50 UTC [9540-3] postgres@test LOG:  disconnection: session time: 0:00:00.021 user=postgres database=test host=xxx.xxx.xxx.xxx port=47706
```
- If you quickly repeat the last step many times you will see following logs on the master:

```
2016-10-24 09:37:58 UTC [21062-3] postgres@test WARNING:  could not establish asynchronous connection after 4000 ms
...
```

and a bit later:

```
postgres@test LOG:  out of file descriptors: Too many open files; release and retry
...
```

It is much easier to reproduce with simple script, e.g.:

``` python
import psycopg2

conn = psycopg2.connect("dbname=test user=postgres")
while True:
    cur = conn.cursor()
    cur.execute('SELECT count(*) FROM testtable;')
    cur.close()
conn.close()
```

During the test you can also check connections status between master and one of the workers:

```
netstat -n | grep "xxx.xxx.xxx.xxx" | tr -s " " | cut -d " " -f 6 | sort | uniq -c
```

there is a lot of `TIME_WAIT` and the number is constantly growing.

I tried following things already:
- I tested the inter-node connection using various tools, e.g. iperf
- I restored default postgresql config to make sure my changes do not affect it
- I increased the max_connections limit (even if I'm sure it wasn't reached)
- I dropped all iptables rules to make sure it doesn't affect the communication
- I tried using `task-tracker` and it was working fine (I could see the same closing/opening connections to the workers but it was not leading to failing queries)

**Comment by ozgune** [comment] 2016-10-24 17:28
@mjaszczyk -- Thanks for the detailed issue report.

We'll assign a team member to reproduce this issue on our end, and we'll post an update to this issue within one week.

**Comment by sumedhpathak** [comment] 2016-10-27 20:17
@jasonmp85 is looking at it, and will try repro'ing it.

**Comment by jasonmp85** [comment] 2016-10-27 20:55
@mjaszczyk, can you post the schema you're using here, how you created your shards, how many shards, etc.? I've executed similar workloads against single- and multi- shard tables using the real-time and router executor and am not seeing anything like what you're describing. It would help to have the full reproduction steps (i.e. the table definitions themselves).

**Comment by jasonmp85** [comment] 2016-10-27 21:09
(In particular, I've created a table with 32 shards, replication factor 1, and am using three workers, like you specify). I've been running an infinite loop of your query for fifteen minutes and haven't seen any leaks (`pg_stat_activity` on the worker shows nothing out of the ordinary).

It might also be useful to know how you've installed Citus. Is this from a package, or did you build from source? If a package, did it come from our repository, or PGDG? If source, did you use a tag, or build from the `release-5.2` branch?

Finally, is there anything else running on your machines? You mention `iptables` rules, so I just wanted to check you weren't running e.g. ay proxies, something like `pgbouncer`, etc.…

Thanks for any details! I'll keep trying to reproduce this and get back to you.

**Comment by jasonmp85** [comment] 2016-10-27 22:53
Ok, I'm still coming up empty-handed. Are you interrupting queries when they run, or letting them run to completion? @ozgune wondered whether this might be related to #671, but I don't see anything in your description about cancellation.

I've tested this on PostgreSQL 9.5.4 atop Debian 8.5. I created a three-node, one master cluster using Citus 5.2.1 and a 6.0 prerelease. Querying in an infinite loop, whether in a single session (`psql` called once), across multiple sessions (`psql` invoked once per query), or via `psycopg2` (your loop) did not produce any connection leaks and even after several 20m runs I'm not seeing any issues.

**Comment by ozgune** [comment] 2016-10-28 02:49
@mjaszczyk -- I also had two quick questions.

1. When you created the distributed table, how many shards did you create?
2. How long are you running your script for? Even when Citus closes the connection, the kernel will keep those sockets in ``TIME_WAIT`` for about 60 seconds. In that sense, seeing more sockets in ``TIME_WAIT`` for a while may be ok.

That said, Citus shouldn't be running out of file descriptors.

On a semi-related note, I've seen the ``could not establish asynchronous connection after 4000 ms`` warnings usually in one of two cases. This happens either when the nodes in the cluster are overloaded and can't accept connections in 4s, or when there's an issue with [DNS settings](https://forums.aws.amazon.com/thread.jspa?messageID=455181).

**Comment by mjaszczyk** [comment] 2016-10-28 14:22
Hi guys,
thanks for spending time on this. Your comments are very useful and I will try to provide more details. I thought that the best would be to just setup another cluster and give you access. Unfortunately I also cannot reproduce it on the new cluster, the only difference is that the new one runs on AWS EC2 while the other one on which I have this problems runs on a bare metal servers. I provisioned this servers using the same Ansible playbooks so the config is 100% the same.

Answering your questions:
> @mjaszczyk, can you post the schema you're using here, how you created your shards, how many shards, etc.? I've executed similar workloads against single- and multi- shard tables using the real-time and router executor and am not seeing anything like what you're describing. It would help to have the full reproduction steps (i.e. the table definitions themselves).

I have single table with about 50 columns (simple values, mostly short ints). The table has timestamp column (`ts TIMESTAMP WITHOUT TIME ZONE`) which is used for distribution (`SELECT master_create_distributed_table('testatble', 'ts', 'hash');`). I have 32 shards with replication factor 2 (`SELECT master_create_worker_shards('testtable', 32, 2);`).

> It might also be useful to know how you've installed Citus. Is this from a package, or did you build from source? If a package, did it come from our repository, or PGDG? If source, did you use a tag, or build from the release-5.2 branch?

I followed the Debian installation guide http://docs.citusdata.com/en/v5.2/installation/production_deb.html

> Finally, is there anything else running on your machines? You mention iptables rules, so I just wanted to check you weren't running e.g. ay proxies, something like pgbouncer, etc.…

No, i'm not using any proxies for PG. Also there is nothing else running on this servers. I flushed all the iptables rules to make sure it is not affecting the connections. Basically it is clean Debian jessie minimal installation with Citus.

> Ok, I'm still coming up empty-handed. Are you interrupting queries when they run, or letting them run to completion? @ozgune wondered whether this might be related to #671, but I don't see anything in your description about cancellation.

I'm not interrupting queries, I also saw this ticket and double checked it before posting this issue.

> How long are you running your script for? Even when Citus closes the connection, the kernel will keep those sockets in TIME_WAIT for about 60 seconds. In that sense, seeing more sockets in TIME_WAIT for a while may be ok.

After each single query there is about 10 connections per worker left over in TIME_WAIT state. Just to be clear, this are connections between master and workers. I can reproduce it having single psql process running and executing queries manually, by running `netstat -nt | grep "tcp" | tr -s " " | cut -d " " -f 5-6 | sort | uniq -c` I can see number of TIME_WAIT per each worker. The numbers are growing quickly. When I was testing it on AWS (on the new cluster I mentioned above) the connections were never remaining in TIME_WAIT, I could only see ESTABLISHED all the time.

> On a semi-related note, I've seen the could not establish asynchronous connection after 4000 ms warnings mostly in one of two scenarios. This happens either when the nodes in the cluster are overloaded and can't accept connections in 4s, or when there's an issue with DNS settings.

The nodes are not overloaded. I also checked the DNS and changed the config so it uses hardcoded IPs instead of names.

**Comment by jasonmp85** [comment] 2016-10-28 22:21
Ok, I've now created a cluster of three nodes, with 32 shards, replication factor two, with fifty columns.

I've tested @ozgune's suggestions, including:

  * Taking down a node while the Python tester runs. `docker-compose` detects this and quickly removes the node from the active list, so requests stop hitting it. I get some errors but they go away.
  * Adding a bad node. Not much stuff happens.
  * Manually adding back a removed node. I get a lot of failure to resolve DNS problems, but nothing else.
  * "Pausing" a node (stopping all processes but not removing it from the cluster or DNS). This produces a TON of "could not establish asynchronous connection" errors since DNS still resolves the host, it is reachable, but PostgreSQL is paused. Closest to what you describe, but when I check out the remaining workers, each has a single connection from the master at any given time, and I never run out of descriptors.

I'll try forcing a `sleep` on all queries to a "bad" node, next.

**Comment by mjaszczyk** [comment] 2016-10-31 14:24
@jasonmp85 I've sent you an email with access to the test cluster on which the issue is 100% reproducable. Hope it will help.

**Comment by jasonmp85** [comment] 2016-10-31 16:47
@mjaszczyk — to be clear, this is the aforementioned "bare metal" Debian cluster, and you still have not been able to build a second cluster that reproduces this issue?

**Comment by mjaszczyk** [comment] 2016-10-31 17:44
Sorry for misunderstanding. I gave you access to the AWS cluster. I finally get the same issue also there.

**Comment by ozgune** [comment] 2016-11-05 18:20
@mjaszczyk / @jasonmp85 -- I wanted to send a quick ping on this issue.

I heard that we had a working theory and just wanted to check it in here. Was the issue that psycopg2 / example script kept transactions open, and that as a result Citus held onto resources associated with open transactions?

**Comment by mjaszczyk** [comment] 2016-11-07 08:09
@jasonmp85 found an explanation for "too many open files" issue which are temporary tables (`.../9.5/main/base/xxxxxx/t2_*`) created on master. They are not being released until transaction is finished. Psycopg2 seems to be opening the transaction by default (http://initd.org/psycopg/docs/usage.html#transactions-control). The issue can be avoided by enabling `autocommit` on the connection. In my opinion this is important limitation to mention in the documentation or try to improve in Citus. So it has nothing to do with connections and I was fixed on this idea so I did not even check other possibilities.
There is another (probably related) issue which I discussed with @jasonmp85 . Once a while there are huge spikes in query latency which are even leading to failures. It might be autovacuum which is pretty active on the master (in opposite to workers). I'm still using the same simple python script, except is has autocommit enabled.

@ozgune @jasonmp85 thank you very much for your help.

**Comment by ozgune** [comment] 2016-11-07 21:35
@mjaszczyk -- sure thing. I'm planning to close this issue. If you have any reservations, could you let us know?

I think we had two issues that were related to each other.

1. PostgreSQL / Citus holds onto certain resources until the end of a transaction. If the client doesn't commit a transaction, PG / Citus eventually runs out of resources. We talked about documenting this behavior in a separate section in our documentation, and I'm cc'ing @begriffs / @sumedhpathak just to keep them informed.

2. Citus creates intermediate files for real-time and task-tracker queries. As a result, clients run into resource related constraints much sooner than they would with Postgres. We have issues #704 and #372 open that aim to mitigate or resolve this issue.

**Comment by mjaszczyk** [comment] 2016-11-08 07:47
Fully agree with you @ozgune although @jasonmp85 might be still working on the query latency issue which we observed on my test setup.

**Comment by ozgune** [comment] 2016-11-08 19:32
@mjaszczyk / @jasonmp85 -- Could you elaborate a bit more on the query latency issue? Is it related to #902?

**Comment by jasonmp85** [comment] 2016-11-08 19:40
@mjaszczyk I do think the other latency issue is `autovacuum`-related, so I'll look into whether we that might be having an adverse effect on our latencies, but I can say that e.g. Citus Cloud has carefully tuned such settings to avoid that issue altogether.

**Closed** 2016-11-08 19:43 UTC
